### ISSUE TITLE
Skip ASO for small files

### ISSUE THREAD

**Issue by bbockelm** [dmwm/CRABServer#4353]
For smaller output files (think <50MB), ASO is overkill.  I propose we add a new output transfer scheme (in addition to the existing "remote" and "local") called "small".

When enabled, if the file is less than 50MB, then a remote stageout to /store/user is attempted.

So, if the strategy is:
["small", "local", "remote"]

and the file is <50MB, it'll first try the remote SE; if that fails, then the local one (and start ASO); if that fails, then the remote SE again.

**Comment by mmascher** [comment]
So, I think we came at a conclusion at the user output review. Use the direct stageout for the first 100 files if they are small (right?)

**Comment by ericvaandering** [comment]
As I understand it, you may have come to this conclusion based on limited if any requests from users. And the draft of that review is yet to be accepted by computing. In fact, I heard conflicting opinions from the reviewers themselves.

As you know I'm not a fan of this, so please remove milestones until I actually get convinced.

What it will take to convince me is that this does not, in any way, increase the debugging load on operations when something doesn't transfer.

**Comment by mmascher** [comment]
Ok, I am actually moving it to the October milestone. I would like to have a milestone for each issue, and October is the one for the low priority/needs a discussion ones.

**Comment by ericvaandering** [comment]
great

**Comment by belforte** [comment]
I believe we will not do this, since:
1. ASO/FTS now groups small files so there's an optimization that we'd loose
2. transfers are usually pretty quick anyhow and will happen even faster once we do those in the PostJob
3. we still have the danger of too many jobs producing too many files at same time and possibly DDOS'sing a remote T2

and mostly, we do not have any real problem to solve here. Can always revisit if really needed.
