### ISSUE TITLE
Resubmitted retries number too big

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4530]
User resubmitted 7 times:
```
twlog.log:2014-11-24 10:18:10,129:INFO:DagmanResubmitter:About to resubmit workflow: 141121_124431_crab3test-2:heilman_crab_FOURTOP_NLO_13TeV_aMCatNLO_LHE_pythia8_AODSIM_v3.
twlog.log.2014-11-21:2014-11-21 16:39:00,858:INFO:DagmanResubmitter:About to resubmit workflow: 141121_124431_crab3test-2:heilman_crab_FOURTOP_NLO_13TeV_aMCatNLO_LHE_pythia8_AODSIM_v3.
twlog.log.2014-11-21:2014-11-21 20:10:43,415:INFO:DagmanResubmitter:About to resubmit workflow: 141121_124431_crab3test-2:heilman_crab_FOURTOP_NLO_13TeV_aMCatNLO_LHE_pythia8_AODSIM_v3.
twlog.log.2014-11-22:2014-11-22 10:41:05,431:INFO:DagmanResubmitter:About to resubmit workflow: 141121_124431_crab3test-2:heilman_crab_FOURTOP_NLO_13TeV_aMCatNLO_LHE_pythia8_AODSIM_v3.
twlog.log.2014-11-23:2014-11-23 09:25:46,229:INFO:DagmanResubmitter:About to resubmit workflow: 141121_124431_crab3test-2:heilman_crab_FOURTOP_NLO_13TeV_aMCatNLO_LHE_pythia8_AODSIM_v3.
twlog.log.2014-11-23:2014-11-23 18:22:41,741:INFO:DagmanResubmitter:About to resubmit workflow: 141121_124431_crab3test-2:heilman_crab_FOURTOP_NLO_13TeV_aMCatNLO_LHE_pythia8_AODSIM_v3.
twlog.log.2014-11-23:2014-11-23 23:43:31,440:INFO:DagmanResubmitter:About to resubmit workflow: 141121_124431_crab3test-2:heilman_crab_FOURTOP_NLO_13TeV_aMCatNLO_LHE_pythia8_AODSIM_v3.
```

Each time he resubmitted number of retries is somehow lost
```
INFO:PostJob This is job retry number 3. The maximum allowed number of retries is 32.
INFO:PostJob This is job retry number 4. The maximum allowed number of retries is 42.
```
http://glidemon.web.cern.ch/glidemon/show.php?log=http://vocms095.cern.ch/mon/cms221/141121_124431_crab3test-2:heilman_crab_FOURTOP_NLO_13TeV_aMCatNLO_LHE_pythia8_AODSIM_v3/postjob.705.3.txt
http://glidemon.web.cern.ch/glidemon/show.php?log=http://vocms095.cern.ch/mon/cms221/141121_124431_crab3test-2:heilman_crab_FOURTOP_NLO_13TeV_aMCatNLO_LHE_pythia8_AODSIM_v3/postjob.874.4.txt
http://glidemon.web.cern.ch/glidemon/jobs.php?taskid=889228

**Comment by mmascher** [comment]
@AndresTanasijczuk , I thought you solved this. Do you confirm?

**Comment by AndresTanasijczuk** [comment]
I implemented a fix (*), but without being 100% sure that it will solve this issue in all possible cases. 
I have not done extensive dedicated tests. The only test I did was to submit a job that I know will fail permanently, I wait until it fails, then resubmit and check that the retry count and maximum allowed number of retries are as expected, and they were. I leave it up to you to decide whether to close or not the issue...

(*) What I fixed is that the maximum allowed number of retries is increased by 3 instead of 10 (https://github.com/dmwm/CRABServer/commit/571eb52957dc814b53bcb926bc378daadd13fbc9).
And actually, I see that I missed to change https://github.com/dmwm/CRABServer/blob/571eb52957dc814b53bcb926bc378daadd13fbc9/scripts/AdjustSites.py#L115. Making a pull request right now for that...
By the way, I added a comment in the code that this number should be the same as in the TW config.

**Comment by juztas** [comment]
Fixed.

**Comment by AndresTanasijczuk** [comment]
@juztas Is it possible to read this number https://github.com/dmwm/CRABServer/blob/master/scripts/AdjustSites.py#L107 from the TaskWorker config instead of hard-coding it?

**Comment by juztas** [comment]
Yes, but this value is not defined in ClassAds AFAIK. I will check then schedds will be fixed. in DagmanResubmitter we can pass everything what is from configuration.

**Comment by AndresTanasijczuk** [comment]
Should we open another GH issue?

**Comment by juztas** [comment]
yes
