### ISSUE TITLE
crab resubmit --force for resubmitting completed jobs

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4683]
```
I already talked with Andres and Marco about this and what Andres wrote
to user how to resubmit these jobs and have their output... sorry, but
it is too complicated (What if I use diff splitting method? EventBased,
LumiBased, FileBased). We can make it much easier without a lot of
effort and without huge effort from users:
`crab resubmit --force --jobids=1,2,3 <task_name>` - This will not check
task status and will resubmit these jobs which user wants (Also output
will be in same directory).

```
Please see: https://hypernews.cern.ch/HyperNews/CMS/get/crabDevelopment/2293/1/1.html

**Comment by mmascher** [comment]
Related to https://github.com/dmwm/CRABServer/issues/4595

**Comment by mmascher** [comment]
Also, make sure we don't screw things with publication (should fail if the lfn is the same, but probably will show the jobs as publication failed)

**Comment by mmascher** [comment]
Two options discussed:
1) invalidate the file before resubmitting if the publication succeded.
2) Don't publish the second retry putting `publish=0` in the couch document

Either way that's tricky if the job is not in a final state.

**Comment by belforte** [comment]
1) simply opens the door to other race conditions.
In the end we need a "kill" which can deal with the fact that the job or the xfer may not the killable.

**Comment by mmascher** [comment]
The `--force` should be used for whatever is not `failed` of `killed`.

**Comment by AndresTanasijczuk** [comment]
So, we have the following 4 things a user can do:

1) `crab resubmit'
2) `crab resubmit --jobids=x,y,z'
3) `crab resubmit --jobids=x,y,z --force'
4) `crab resubmit --force'

What should each one do?

1) Resubmit all failed and held  jobs in the task.
2) Resubmit jobids x,y,z only if their status is either failed or held.
3) Resubmit jobids x,y,z only if their status is either failed or held or successful.
4) What to do here? Same as 1), or Resubmit all failed, held and successful jobs in the task? I would say do same as 1), i.e. the `--force' has no effect if not combined with a list of jobids.

**Comment by ericvaandering** [comment]
Seems to me 4) should not be allowed. The "logical" thing to do in that circumstance is resubmit al finished jobs but why would someone do that? They should just re-run the workflow.

**Comment by belforte** [comment]
@ericvaandering +1
@AndresTanasijczuk why do we have held jobs ? crab resubmit will make a new job, will something in the meanwhile release the held jobs ? If they will not be releases, why are they held ? Is user expected to know the difference between held and failed ?
@mmascher  and @bbockelm and @ericvaandering Overall.. do things really need to be so complicated that we have difficulties to agree on what resubmit does ?

Seems I keep finding things that were done possibly not optimally, but at least clearly, consistently and w/o users being confused in Crab2.

**Comment by AndresTanasijczuk** [comment]
Coming back to this issue as I think we would like to include it in next release.

@ericvaandering I agree with your statement that the "logical" thing to do in case the user does `crab resubmit --force` is to resubmit all finished (and held/killed) jobs. As per if that makes sense or not, I have no strong opinion, so I will do what you suggested, i.e. not allow `crab resubmit --force`.

**Comment by belforte** [comment]
+1
@AndresTanasijczuk can you comment on the resubmission of Held jobs ?

**Comment by AndresTanasijczuk** [comment]
Answers to @belforte 
Q: "why do we have held jobs?"
A:
Actually, I have never checked (neither by submitting jobs nor from looking at the code) if we can have held jobs or not. The condition that a job has to be in status `failed` or `held` to be able to be resubmitted was there since long time and I didn't question it much. Actually, there was another allowed state for resubmission, which was `cooloff`, and it was that one which I questioned and at the end we decided with @mmascher to allow only `failed and `held`. We questioned with Marco also the `held` state, but we assumed that it was for killed jobs. I.e. we assumed that a job could be put on hold when the user does `crab kill`. But seems it is not the case; we checked with @juztas that under `crab kill` jobs should be removed. So your question "why do we have held jobs?" makes much more sense now to me. We checked the status code called by the resubmit in https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/DataWorkflow.py#L380 The status code is in https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/HTCondorDataWorkflow.py#L241 The actual function being used under verbose=0 is https://github.com/dmwm/CRABServer/blob/master/src/python/CRABInterface/HTCondorDataWorkflow.py#L868 (read the job states from the node_state file) which, if we read the code correctly, implies that a job status can never be 'held'. If we would instead use verbose=1 the status would read from the jobs_log file, and in that case 'held' is a possible status. But we have the periodic remove reason to remove jobs held for more than 7 minutes. So at the end I am starting to think that we should not include `held` as an allowed state for resubmission. 

Q: "crab resubmit will make a new job, will something in the meanwhile release the held jobs ?"
A:
Under `crab resubmit` the condor_dagman job will be killed and a new condor_dagman job started. The new condor_dagman job will read the DAG .nodes.log file to catch up the status of the nodes and decide which ones are resubmitted. I don't know what happens if a job was on hold when the condor_dagman was killed.

**Comment by belforte** [comment]
Good so we converged on: only resubmit FAILED jobs.

Do we have any Periodic Release expression ? You make it sound like we do not, but would be know for 
sure. In particular this must go in some CRAB3 DESIGN document which we keep uptodate and trust as 
The Bible, less someone decides to introduce a Periodic Release at some time and screw up everything.

About the last thing, I fear if you kill the DAG, held jobs stay there. So it is good that we 
Periodic Remove them :-)

**Comment by AndresTanasijczuk** [comment]
@mmascher Should I remove `held` as an allowed job state for resubmission and only keep `failed`?

**Comment by mmascher** [comment]
I discussed with Andres, yes, let's only keep failed.
