### ISSUE TITLE
[improved job splitting] Write out sub-dags for unprocessed lumis

### ISSUE THREAD

**Issue by matz-e** [dmwm/CRABServer#4692]
Issue to keep track of implementation status: @annawoodard @bbockelm

We need to write out a (or overwrite an empty) sub-dag with the job definitions to process leftover lumi sections.  Submission should be automatically by condor?

See [docs](http://research.cs.wisc.edu/htcondor/manual/v8.3/2_10DAGMan_Applications.html#SECTION003108800000000000000)

**Comment by matz-e** [comment]
@bbockelm I'm currently working on this.  I have hooked up empty SUBDAGs for every job. (BTW, does this create too much of a load on the submit node, as every SUBDAG is run as its own condor job?)

Next steps:

- [ ] Factor out DAG + submission description fragments and parameters out of `DagmanCreator`
- [ ] Take said bits and use them in the PostJob to fill the SUBDAGs
- [ ] Save and use splitting results with remaining lumis (WMCore splitting is available to the PostJob)
- [ ] Update `run_and_lumis.tar.gz`.
  Is there a better way to do this?  I'm slightly worried about overwriting the tarball while it may be accessed by other jobs.  I could remove the hard-coded values in the scripts, and create additional run and lumi tarballs on a SUBDAG level.

**Comment by mmascher** [comment]
The overwrite thing can be handled by writing a temporary file first and moving it to `run_and_lumis.tar.gz` then, or with a file lock if necessary (I have been using `fcntl` in the PostJob). But if you think the additional runlumi tarballs are more clear please go ahead. I personally prefer new run_and_lumis files popping up rather then havin the main one being modified (which can go unnoticed)

**Comment by belforte** [comment]
what is this exactly about ?
dealing with lumis left out by job splitting ? (why?) or recovering for failed jobs ?
iteratively split jobs into smaller sub-jobs if initial splitting is found out not to be optimal ?
I am really worried when things get so complicated.  Which exact problem do you want to solve here, which does not have an acceptable solution yet ?

**Comment by matz-e** [comment]
Recovery.  Brian's original idea was to take the user out of the equation for job splitting:

* user provides dataset + pset
* crab uses dryrun to estimate time / event
* event aware, lumi-based splitting allows to get jobs within a certain pre-configured runtime
* CMSSW stops after pre-configured runtime maximum
* PostJob collects all lumis that might not have been processed
* smaller jobs process leftover work

**Comment by belforte** [comment]
gotcha. Cool, but a long shot. Shound not understimate of course the possibility that user code of procedure is way sub-optimal and keeping some pressure on user may be good, in the end.
People do not usually _need_ 100% completion e.g.

**Comment by annawoodard** [comment]
> Shound not understimate of course the possibility that user code of procedure is way sub-optimal and keeping some pressure on user may be good, in the end.

We are currently asking people: given dataset X, determine how many jobs it needs to be split into in order for each job to run for 8 hours. This question is tedious to answer and we shouldn't be surprised that people often get it wrong. In the case of lost productivity (and wasted computing resources) due to bad splitting parameters, I think we have everything to gain by solving this problem on our side, and not much to gain by 'keeping pressure on the user'.

> People do not usually need 100% completion e.g.

I disagree, @belforte (if I understand correctly). People *certainly* need 100% completion in the not-so-unusual case that they are running on collisions data!  :-)

**Comment by belforte** [comment]
yes @annawoodard we disagree :-) Which is good since this is not a clear cut situation. Surely many users need and deserve us to make their life easier, as you say. Surely there will be someone who submits tons of useless jobs, but that's a different story.
About 100% statistics... that's a different story. At some point it is nice that we publish analysis based on X fb-1 of luminosity, not 0.98*X, but I'll be curious to see one result where the extra 2% luminosity makes any difference in the physics conclusions, even the statistical uncertainty will not be different. But indeed it is not a discussion to have in here, CRAB should do its best to give 100%.

**Comment by matz-e** [comment]
As a user, I want my jobs to all finish.  I see this project mainly as a convenience.  I don't want to find out how much time per event I exactly need, how many events there are per lumi in a dataset (of which I have ~50), etc...  All I want, as a user, is to say "take this dataset, configuration, and turn them into 4 hour long jobs."  Then I know that (overflow included) most jobs should be done in at most ~6 hours, even if they land on a slow resource.

**Comment by annawoodard** [comment]
After discussion with @matz-e, I'm looking into this now, starting from his [branch](https://github.com/matz-e/CRABServer/tree/automated_splitting). I'll go with @mmascher's suggestion of `fcntl` + tempfile to append the new lumi masks to `run_and_lumis.tar.gz` (leaving the original ones unmodified). In this way most of the dag machinery can be re-used. I will use 1-1, 1-2, 1-3, etc to denote sub-jobs of job 1 (as opposed to 1.1, 1.2, 1.3, etc, to denote retries of job 1), unless there are any objections.

**Comment by matz-e** [comment]
Done with the merging of automated splitting.
