### ISSUE TITLE
print CMSSW log if job is removed by periodic_remove

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4699]
8.3.3 version is returning log files, but CMSSW output does not exist. Need to install a signal handler in CMSRunAnalysis.py and invoke logCMSSW (https://github.com/dmwm/CRABServer/blob/master/scripts/CMSRunAnalysis.py#L270) before exiting.
(you also want to make sure to re-throw the signal)

**Comment by bbockelm** [comment]
FYI - currently, HTCondor sends SIGTERM to all processes in the job.

**Comment by mmascher** [comment]
Be aware that `logCMSSW` is stripping the cmsRun output. If we want the whole output we need `cmsRun-stdout.log`.

**Comment by belforte** [comment]
Good point Brian. I presume that means something like
for all-processes-in-the-tree: send sigterm (w/o pause)
not send to the parent and let it percolate via standard way (i.e. if not trapped)
This means job wrapper will get SIGTERM before cmsRun has completed processing the same signal (cmsRun will need a bit of time to close gently). And may casue a race in updating FJR and other stuff. By the way, since jobwrapper gets a nice SIGTERM there is no reason not to trap it and (in addition to Cancel Reason in condor log) set a decent exit code to help us classify jobs in dashboard. Also at times one SIGTERM is not enough to kill a preocess etc. Bottom line, I think it will be good to review how external termination is handled.

**Comment by juztas** [comment]
I started looking into this and a bit confused.
a) Catch SIGTERM, print CMSSW log and raise SIGTERM again
b) Catch SIGTERM, identify cmsRun/scriptEXE PID, send SIGTERM and let all other functions to finish.

P.S. If job is removed due to periodic_remove, we are not reporting anything to dashboard. PostJob is setting these jobs as failed. If (b):
     1) Identify in job why it got SIGTERM and report correct information.
     2) Report ExitCode from PostJob,which is known in the Postjob and it knows why this job was removed

**Comment by bbockelm** [comment]
Hi @juztas,

You could actually do either (a) or (b).  I would recommend (a) myself.

You don't *have* to exit immediately on SIGTERM (as in (b)), but at some point in the future (you don't know when), the process will get a SIGKILL and all output would be lost.  I'd rather have truncated output as in (a) than lose everything.

In terms of reporting this:
1) We should set PeriodicRemoveCode (in addition to PeriodicRemove and PeriodicRemoveReason) to evaluate to an identifiable integer when evicted for memory / walltime.  This will allow glidemon to pick up the exit reason.
2) We should send a message to dashboard, even in (a).  We can do one message from the job wrapper (as we know the job is no longer running) and get a more accurate exit code from the post-job and send an updated message then.

Brian
