### ISSUE TITLE
get rid of gsissh and have all directories created on scheduler

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4752]
Seems this happens again, and I have this in my todo, creating issue for not forgetting and for identifying good solution for this.
Please check these 2 links:
https://ggus.eu/index.php?mode=ticket_info&ticket_id=112942
https://hypernews.cern.ch/HyperNews/CMS/get/crabDevelopment/1930.html

**Comment by bbockelm** [comment]
Farrukh and/or Ivan may have some suggestions on how to do this via Puppet @ CERN...

**Comment by mmascher** [comment]
Even if we removed the `gsissh` dependency on the TaskWorker we would still have to contact argus on the schedd, right? So I guess this would not solve the problem we are facing lately with submission taking up to 30 minutes because of argus timeouts. Is there a way to remove the argus dependency at all?

**Comment by belforte** [comment]
yes it would not solve.
We can fall back from Argus to gridmap files.
Was discussed some time (1 year?) ago with Preslav, but at the time eventually CERN mnaged to improve Argus stability.
What bother me now is the lack of news from IT.  Submissions to CERN CE's and all pilots trying glexec should be similarly affected and result in clear degradation if not failures at large.
Generally speaking I prefer a service CERN maintains, even if it failes one day/year, to something that we setup ourselves. Een if something as simple as gridmap.

**Comment by bbockelm** [comment]
Hi,

HTCondor will at least cache the argus callout for a fixed period of time.  I don't recall what it is set to currently, but we can probably crank it up to 2 days.

Brian

**Comment by juztas** [comment]
If I recall this correctly: gsissh dependency from TW is needed only once to each schedd (To create home directory). If I submit a task first time in my life, we need to do gsissh, next time it is not needed to do gsissh, because directory already exits.
About 2 days, don`t think that it can make any problem, but now it can wait for Monday :)

**Comment by juztas** [comment]
Other thing why, When we were preparing for Amazon EC2 presentation and test, gsissh was removed from TW. I have not followed a lot local submission and might be incorrect, but if it will be allowed to submit through our maintained CS and TW, in that case sites which want local submission will also have to have gsissh daemon.

**Comment by belforte** [comment]
or those sites can create all needed home directories beforehand.
Which would be preferred even at CERN. If we come to that we can
always ignore gsissh error based on schedd domain :-/

**Comment by juztas** [comment]
@bbockelm @belforte @mmascher do we all agree to increase caching to 2 days ?

**Comment by mmascher** [comment]
Fine with me

**Comment by belforte** [comment]
what is it now ?
Would we cache mapping, or authz as well ?
Currently we rely on Argus for quick banning of DN's in case
of security incidents. Taking 2 days to notice this is a bit too much.

**Comment by juztas** [comment]
https://cms-logbook.cern.ch/elog/GlideInWMS/1832 
https://ggus.eu/index.php?mode=ticket_info&ticket_id=112942

This started to happen again and it is increasing (Mostly for Dmytro). First, no one has an alarm on this and only operator notice if he checks it. 

What it would cache, see https://htcondor-wiki.cs.wisc.edu/index.cgi/tktview?tn=4138

**Comment by belforte** [comment]
After reading that, I would stick with 2h caching. Could certainly put 4h, but I doubt it makes a difference, only we notice a bit later the onset of the problem. Purpose here is to relieve load due to making multiple access for the same user while e.g. processing multiple jobs in same task. Not really to provide backup for operations.   Argus dies, we stop, it is a critical service for CERN.
A couple bad days a year are not worth worrying about.  Mitigation is always useful, but strategy depends on the failure more of Argus,  current problem does not seem due to load and longer caching would not help on something that is lasting since days.

A different story would be to for a static gridmap, that has very good performance but is operationally more heavy as we take on us the burden to make sure the map is always up to date.

**Comment by juztas** [comment]
puppet changes for creating directories done in qa branch:
```
# Create all grid users home directories
  define createDirs {
    file { "/home/grid/${name}":
      ensure => directory,
      mode => 0755,
      owner => "${name}",
      group => "zh",
      require => Class["hg_vocms::modules::condor"],
    }
  }

  $users1 = range("cms001", "cms999")
  $users2 = range("cms1000", "cms1999")
  $users = concat($users1, $users2)
  createDirs { $users: }
```
https://git.cern.ch/web/it-puppet-hostgroup-vocms.git/commitdiff/36a54fbcd33cce9c6c9fee61c9c97dad5c26d706?hp=1d4a697c2500ccd0c6cd2d35d608e13a2eb724c9

First puppet run will take a lot, because it has to create all directories. Whenever this will go to master branch, we can remove gsissh.
@Farrukh-Aftab

**Comment by belforte** [comment]
assigned to Justas since closing depends on the resolution of the PR he made on June 30 #4858

**Comment by belforte** [comment]
that PR was closed, so let's close this Issue as well
