### ISSUE TITLE
show single jobs states even if status failed

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABServer#4806]
Currently, when task status is FAILED in the task database, crab status doesn't return the status of single jobs.

**Comment by belforte** [comment]
this are currently worse than this issue title suggest, users get a very horrible and confusing message like

Error reason: Trapped exception in Dagman.Fork: <type
'exceptions.RuntimeError'> Error when performing action on the schedd.

see e.g. 
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/733/1/1/1/1/1.html

**Comment by AndresTanasijczuk** [comment]
My original comment was incomplete. It should have been: when task status is FAILED in the task database, crab status doesn't return the status of single jobs. It only returns the task status (= FAILED) and the failure message (if any) from the task database.
In https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/733/1/1/1/1/1.html the error  

Trapped exception in Dagman.Fork: 'exceptions.RuntimeError'> Error when performing action on the schedd.

occurred during a 'crab resubmit' (the error is then uploaded to the task database and the task status set to FAILED).

**Comment by AndresTanasijczuk** [comment]
So the "Error reason" printed by 'crab status' is always real, in the sense that it is the error that caused the task status to become FAILED.

**Comment by belforte** [comment]
Sounds there may be more than one thing to fix then.
1. list individual jobs status (as this issue say)
2. the task should not become permanently failed if the error was recoverable, in any case it is not good to ask users to do resubmit --jobid listing all jobs in the task rather then simply resubmit,
 why the server (client) can't do a loop on the job id's  if that works ?
3. then the dagman.fork failure is still an non-understood/non-properly handled problem, I agree that the error is real, but should not be exposed to users like that if the problem is something known to possibly happen. The only reason to print such a message and traceback is "something bad and unexpected happened, report it to developers so that it can be fixed"

I am not complaining with you Andres, but simply the whole thing of errors in talking to server, and in servers talkgin to TW and TW talking to HTC is still not handled well enough. We need to reach the point where users find in the message itself the explanation and recovery action, w/o need to write to us.

**Comment by AndresTanasijczuk** [comment]
About 2., we don't ask users to do 'crab resubmit --jobids'. It is the other way around. 'crab resubmit --jobids' doesn't work in this case and what does work is 'crab resubmit'. So we ask users to omit the --jobids option, in which case CRAB will resubmit all failed jobs. The --jobids option is useful for users to resubmit a subset of the failed jobs. In the case of Bockjoo, he was giving --jobids with ALL the (6) jobs that were in failed status. Clearly not necessary, as CRAB would identify these jobs automatically if --jobids would be omitted.

**Comment by AndresTanasijczuk** [comment]
We could modify the resubmission code to work also when --jobids is given. But I think that, if we fix 1. there is no need for changing anything in the resubmission code.

**Comment by belforte** [comment]
ah !! Thanks, I got this detail fully wrong then. Take this as a measure
of how much esoteric this stuff has become :-(
