### ISSUE TITLE
CRAB should not refuse to submit anything if site list and data location don't allow ALL data to be analyzed

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRABServer#4823]
See https://hypernews.cern.ch/HyperNews/CMS/get/crabDevelopment/2347.html

**Comment by belforte** [comment]
this is not urgent. So far DDM policy is to replicate entire datasets, not scatter them around.
Once we will have very large datasets that can happen, but it is not the case now.

**Comment by belforte** [comment]
this became urgent because the situation is triggered also by new blocks inserted in DBS as closed  but in PhEDEx as open, thus leading to blocks w/location.
See
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/958/2/1/1/1/1/1/1/1/1/1/1/1/1/1/1.html
and
https://hypernews.cern.ch/HyperNews/CMS/get/dmDevelopment/1842.html

**Comment by belforte** [comment]
maybe we can make it by the October release ?

**Comment by AndresTanasijczuk** [comment]
I am working on it. @belforte, is it in general true that all files in a block have the same locations?

**Comment by belforte** [comment]
Yes, it is true. it is part of the basic design of the model. 
At first sight, in DBSDataDiscovery.py we can simply remove from the list a block with no location here
https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/DBSDataDiscovery.py#L101

The only drawback is that ignore_location will not process data with no location, but I think that is rather an advantage.

**Comment by mmascher** [comment]
The blocks are already removed in `keepOnlyDisks`, but the WMCore API we use (`listFileBlockLocation`) to get the locations of the blocks looks for them in DBS if phedex answer `[]` (using `listBlockOrigin`). So at the end of the day the block has one location (`T0_CH_CERN_Export` IIRC) . Then at a successive step we convert this to a PSN and we get an empty list. Notice that since the block has not been removed earlier it will be used with `ignore_locality`!


Let me summarize what we should do imho. This list is biased because I am taking into consideration the current implementation, I don't think we want to rewrite the discovery, splitting, job creation and so on..

1) Get all the blocks of the dataset from DBS.
2) If the dataset is in global delete blocks open in phedex (should we warn the users?). This is done(ish) here https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/DBSDataDiscovery.py#L62-L64 since using `complete='y'` in the phedex location discovery gets an empty list https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/DBS/DBS3Reader.py#L574. But then the WMCore code fallback to DBS (which is done to account for for USER dataset)
3) Get the locations of the blocks using phedex or dbs (maybe now we can assume that if locations in phedex=[] then it's a user dataset where locations has to be looked up in DBS)
4) At this point I would assume a block always has a location (there is a custodial site in phedex and there is always a location in DBS). That said don't assume it in the code and warn the user if it's not the case. Maybe don't remove the block since maybe we might want to run with `ignore_locality`. I am worried here about old user datasets with an SE instead of a PNN in DBS where the PNN cannot be looked up..
5) Get the PSN of the block. It's likely now that some PNN does not have a PSN associated and you end up with an empty list of processing locations. Again warn the user and don't remove the block so we can run with `ignore_locality`. Warning message should be different of course!
6) Run the splitting algorithms (they requires the locations for the blocks IIRC)
7) Create jobs. Now we apply the white/black lists and again there might be blocks with an empty list of processing locations. Again warn the user with a different error.
8) Submit the jobs, skip blocks that for one reason or another have no locations, and submit to the other ones.

**Comment by belforte** [comment]
@mmascher sorry I am quite busy with similarly interesting debates on information system in CMS and WLCG. And this discussion is getting too long. Maybe you rewrite a shorter description of the proposed new flow ?
Most of all I would take a fork right at the beginning and separate global DBS from phys03. In the first case, only use PhEDEx location info, in the  second fully ignore PhEDEx. Yes, it makes CRAB know something about the way CMS dataset bookeeping is organized, rather than transparently hide it.

**Comment by mmascher** [comment]
Yeah, I made a summary here: https://hypernews.cern.ch/HyperNews/CMS/get/dmDevelopment/1842/3/1/1/2/1/1.html

I think I'he got everything under control now :)

**Comment by AndresTanasijczuk** [comment]
What should we do with this issue now that we have a working patch?

**Comment by belforte** [comment]
close as soon as the working patch is in a tagged release
