### ISSUE TITLE
support group datasets

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#4825]
allow more users to contribute to the same dataset.
When storage location is /store/group/groupname instead of /store/user/username put groupname instead of username in the published dataset name.

Question : do we put group or user name in LFN ?
Will ask the group who is initially intersted in this (ECAL calibrations)

**Comment by belforte** [comment]
see:
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/654/1/2/1/1/1/1/1.html
and in particular
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/654/1/2/1/1/1/1/1/1/1.html

**Comment by AndresTanasijczuk** [comment]
Also https://hypernews.cern.ch/HyperNews/CMS/get/crabDevelopment/1999.html taken from https://github.com/dmwm/CRABServer/issues/4308

**Comment by AndresTanasijczuk** [comment]
Q1: Do we want to always put groupname instead of username in the publication dataset name, or do we want to have a switch (e.g. Data.useGroupName... = True or False) to turn this feature ON/OFF (with default to False I would say)? I think we have to assume the user wants to keep its dataset private by default.

Q2: Aren't there cases in which user areas are in "fake" /store/group/ areas? I did a quick search in the Computing Tools forum history and found for example this https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/477.html Having the switch I propose in Q1 would avoid problems in such cases.

Q3: Is it safe to assume the groupname is the 3rd field in Data.outLFNDirBase = '/store/group/...'? Otherwise things get complicated.

Regarding Stefano's question "do we put group or user name in LFN ?"
CRAB is not adding the username to the LFN. (See https://twiki.cern.ch/twiki/bin/view/CMSPublic/Crab3DataHandling#Logical_File_Names_of_output_and) The username appears in the LFN if:
1) /store/user is used
2) the user explicitly adds it in Data.outLFNDirBase parameter
Are you proposing that CRAB should add the username in some place of the LFN when Data.outLFNDirBase = '/store/group/...' ? Remember in the past we were enforcing users to put their username in Data.outLFNDirBase also for /store/group and ended up removing this enforcement because we got complains.
I think we should not change anything in the LFN from what is being done now.

**Comment by belforte** [comment]
A3. yes
about LFN, OK to not change anything.
about Q1 and Q2, I need time to understand

**Comment by belforte** [comment]
was pessimisting. I think I understand Q2 and I think that is what drives Q1. Indeed there are cases where group name in dataset name makes no sense. Let's try to find the simplest solution

**Comment by AndresTanasijczuk** [comment]
But if you accept that Q2 is indeed possible, is still your A3 'yes'? 
I would say that if we have the switch I propose in Q1 and the user sets it to True, then we assume A3 is 'yes' and delegate responsibility to user.

**Comment by belforte** [comment]
I am leaning toward answering YES to all questions indeed.
WIll try to think of a better name than :
Data.useGroupNameInsteadOfUserNameInDatasetName
but that's indeed the semantic

In the end the chance of two users picking the same dataset name by chance is
likely smaller than initially feared, but I do not know how to tell how much we need to force the dataset name in this way rather than leaving it fully free.
I.e. I am wondering if we still make this more complicated than it needs to be

**Comment by belforte** [comment]
@AndresTanasijczuk what did you call the configuration parameter in the end ?
I looked at the changed files in the PR but could not really tell, but  I guess it is not
 Data.useGroupNameInsteadOfUserNameInDatasetName

as a different comment, I am amazed how many files needed changing, do we keep building the dataset name over and over in many places ?

**Comment by AndresTanasijczuk** [comment]
@belforte The configuration parameter is in a corresponding PR in CRABClient: https://github.com/dmwm/CRABClient/pull/4504 It is named "Data.publishGroupName". Of course the name of the parameter can be changed. Mine is just a proposal so that we have something to start on. And I try to keep same names in client and server. On server the parameter is named publishgroupname.

The publication dataset name at the end must be inserted in the output filemetadata (ASO retrieves it from there). The publication dataset name is currently fully build in the post-job (which is btw who uploads the filemetadata) using the following pieces:
a) the primary dataset name;
b) the username;
c) what we call the publishDataName given by the user in the CRAB config;
d) the pset-hash taken from the FJR;
e) the string "USER";
f) the PoolOutputModule label -as taken from the FJR- of the corresponding output EDM file (this only in case there are more than 1 EDM files to publish).
I can guess that the main reason why the publication dataset name is build in the post-job is because of d) and f).
The publication dataset name is also partially build in the server (REST) so to validate it. We validate separately:
a) the primary dataset name;
b) the B part of /A/B/USER, but using a checksum instead of the final pset-hash and without the PoolOutputModule label.
This PR has to change the username by the groupname in part B of /A/B/USER, so it has to modify the way the publication dataset name is build in both the post-job and the server.
While I was working on this PR I also realized that this is not good. But I was lazy to improve this now.

The many files that needed a change is also because of saving the new parameter in the Oracle Task DB, which I would wish we have an easier way to do that. Something like we have in the client. Adding a parameter in the CRAB config in the client side is very simple. But adding a parameter in the server side requires changes in many places.

**Comment by belforte** [comment]
I think if you change to Data.publishWithGroupName or data.publishUsingGroupName  it is more clear.

About the complexity of adding a paramter to Oracle in Crab Server, it is easy to agree, but it is 
for Marco to review and possibly do better.

**Comment by AndresTanasijczuk** [comment]
Ok, will change to Data.publishWithGroupName in the client.
