### ISSUE TITLE
Report correctly to dashboard when files are read remotely 

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4859]
More details: https://hypernews.cern.ch/HyperNews/CMS/get/crabDevelopment/2364/3/1/1.html

**Comment by bbockelm** [comment]
Do we have any proposal on the table what it means for a "file to be read remotely"?

**Comment by juztas** [comment]
I would say if any file is read remotely (1), we mark this job as remote read.

(1)
a) multiple files and one file is read remotely
b) if dataset is on site A and job ran on site B, definitely remote read.
c) (?) job run on site A and dataset is on site A and if failing to read file locally, if fallback was used in CMSSW, also remote read. (Need to take a look what we have in FJR.xml and can we determine it)

**Comment by bbockelm** [comment]
(One problem is that the "fallback" is not necessarily visible to CMSSW (at FNAL or DPM sites) because Xrootd might do the redirection transparently.)

But that's not the "big picture" problem.  What I'm really concerned with is folks doing comparison studies of local/remote based on this data when we know there are many false positives and false negatives.

What if we say the job read remotely only if *all* files were accessed through fallback?  That way we can say something definitive for the jobs labelled 'remote', even if we can't say anything about the ones labelled 'local'.

Alternately, what about having a tristate?  "All local", "Mixed", and "All remote"?  This would make the data better for Jose to analyze.

**Comment by belforte** [comment]
not relevant anymore, we'll see about this when we finalize reporting to new CERN MONIT
