### ISSUE TITLE
validation 1507

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4862]
This pull request https://github.com/dmwm/WMCore/commit/6a1ae7d6b0d26df89b6296d870bd0634a02f7ac9 affected CRAB3 this part: https://github.com/dmwm/CRABServer/blob/master/scripts/CMSRunAnalysis.py#L695-L701

**Comment by mmascher** [comment]
Hi all,

a couple of things to check:

Server Stuff:
* Usage of PNN instead of PSN for checking ASO destinations: try to put names that are PNN but not PSN as destination, like T1_US_FNAL_Disk and see if this is accepted
* Check in the logfiles if we are reporting the correct number of events where there are multiple file read
* Less CPU usage thanks to the enabled JOB_HISTORY_DIR [Done]
* Try to submit to a schedd that goes to timeout doing gsissh and see that we do not wait indefinitely (I have one of such schedd)
* Verify we print the environment variables in the postjob
* Try the `Data.publishWithGroupName = True`. LFN has then to start with `/store/group/<groupname>` and groupname will then used in place of the `username` in the publishname. Since we do not have a CRAB3 groupspace (despite having requested it many times :() I suggest to use one of the T2 that does not check permissions for that
* Check reporting of exit codes, especially for jobs removed for memory and walltime limits

**Comment by juztas** [comment]
So we are missing publishWithGroupName and we did not got group space due to miscommunication.

**Comment by mmascher** [comment]
Client:
* Try to run on an invalid dataset and then use allowNonValidInputDataset (that's actually also a server's issue)
* See if the logfiles are there, also using the CRAB library. Before in some cases the output was not flushed on the disk
* Use `setConsoleLogLevel(LOGLEVEL_MUTE)` in the crab library to change the logging level and not print in the output
*

**Comment by AndresTanasijczuk** [comment]
Just tested setConsoleLogLevel(LOGLEVEL_MUTE) and getConsoleLogLevel() in the crab library using production client. They work fine. Also the crab.log files are there with all the logging as in a regular crab command.
For the non-VALID datasets feature, works when dataset status is PRODUCTION. For other non-VALID states we have to wait for https://github.com/dmwm/CRABServer/pull/4866; currently one gets:
```
Task status:			FAILED
Warning:			The dataset you are analyzing is not 'VALID' but 'INVALID'. CRAB3 will try to see if there is any valid file.
Error during task injection:	Cannot find any valid file inside the dataset. Please, check your dataset in DAS, https://cmsweb.cern.ch/das.
Aborting submission. Resubmitting your task will not help.
```

**Comment by belforte** [comment]
crab 1507 was deployed. Let's close its validation
