### ISSUE TITLE
Randomize injection loop

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#4873]
The injection loop in the Task Worker [1] goes like NEW, KILL, RESUBMIT.

That means that we first add tasks in the state NEW, then we add tasks in the state KILL and finally we add tasks in RESUBMIT. In case of high schedd load, and tasks accumulating in the oracle DB, what happen is that the task worker queue might be saturated with tasks in NEW.

That's what happen with tasks in RESUBMIT that were processed at last (I actually had to increase the size of the queue to 20 to get tasks processed)

I propose to "randomize" the order the states are processed. I don't think NEW tasks should have a priority over other tasks.

[1] https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/MasterWorker.py#L240

**Comment by belforte** [comment]
I thought I commented, but somehow went lost.
I think random is a bad idea here, makes behavior different every time and debugging difficult.
I would have rather taken care of things in "reduce load" order:
1. kill (reduce #tasks to look after)
2. resubmit (close existing tasks)
3. new (FIFO for users)

But this is really not a cure for anything and smells of  ad-hoc reaction to the trouble of the day, likely to result in oscillating behavior. Why can't tasks pile up in schedd ? Don't we have enough schedd's ?
Why did you need to increase some queue  ? Which queue is it, and how is dimensioned and what happens when it is full ?

I.e., if the order or this loop matters, other things are likely not clear, not understood, not working or some combination, and changing the order here will hardly lead to no long term improvement.

**Comment by mmascher** [comment]
We agreed at the meeting that the best thing to do would be to get all the works (`RESUBMT`, `KILL`, `NEW`) in one call instead of three (and of course ordered by time). Anyway, for the moment let's keep this.
