### ISSUE TITLE
Move reporting of logs url to dashboard from CMSRunanAnalysis to the prejob

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#4906]
It saves some code and guarantee the logfiles are there when the jobs are idle (even though they will not contain anything significant)

Also consider to remove the reporting from the postjob so that we can remove some code and avoid to set the two classads (CRAB_UserWebDir and CRAB_UserWebDirPrx).

**Comment by emaszs** [comment]
Discussion with Marco:
In order to simplify and shorten code, reporting of job logs can be done in one place instead of two.

That would mean removing classads 'CRAB_UserWebDirPrx' and 'CRAB_UserWebDir' (https://github.com/emaszs/CRABServer/blob/master/src/python/TaskWorker/Actions/PreJob.py#L319-L332)

Also modifying and moving the reporting code https://github.com/dmwm/CRABServer/blob/0bf4848e1a08e869a66eb946503fb66da1cd7e73/scripts/CMSRunAnalysis.py#L98-L103
to here: https://github.com/emaszs/CRABServer/blob/master/src/python/TaskWorker/Actions/PreJob.py#L119

**Comment by emaszs** [comment]
After investigating with @AndresTanasijczuk and @juztas we've added a SyncGridJobId key (and correct value) to update_dashboard() params dict in PreJob. That seems to work fine for reporting the logs to dashboard. 

We've also removed a check "if crab_retry != 0" when calling update_dashboard() from PreJob execute(). We weren't sure why this was necessary, perhaps someone can comment.
