### ISSUE TITLE
SE being down is not recoverable error

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#4908]
```
56bc3bf367a9231e72b786b19947649765c2db322898b00e429226ad:
                  -----> ASO log start -----
                  ['DESTINATION OVERWRITE srm-ifce err: Communication
error on send, err: [SE][srmRm][]
httpg://se.hep.fsu.edu:8443/srm/v2/server: CGSI-gSOAP running on
lcgfts07.gridpp.rl.ac.uk reports could not open connection to
se.hep.fsu.edu ']
                  <----- ASO log finish ----
                  The last failure reason is recoverable."
```
Tried to ping or connect to SE without success. Even ASO with 3 retries all times failed (With timeout between transfers 2h).

Change to not recoverable?

**Comment by belforte** [comment]
try again tomorrow ?

**Comment by juztas** [comment]
user can, but he has to resubmit and we should not retry to run job. We can't say to jobs wait 24h before start to run (Or do we?)

**Comment by juztas** [comment]
Not creating another ticket, but this has to go to same check if job is recoverable or not
```
 -----> ASO log start -----
 ['TRANSFER  globus_ftp_client: the server responded with an error 452 Insufficient resources: diskCacheV111.services.space.NoFreeSpaceException: space with id=31334553 does not have enough space   ']
 <----- ASO log finish ----
```

**Comment by mmascher** [comment]
About the pull, I am conviced about `".*does not have enough space.*",` , but I am not so sure about ` ".*reports could not open connection to.*",`. to me the latter smells like a recoverable arror, although it's just an impression and we know how error messages could be deceiving sometimes.

**Comment by belforte** [comment]
generally speaking, when jobs are retried, are they simply re-queued in condor right away (with priority) or is a delay enforced ?

@mmascher the question is whether FTS retried already. If it did, transient connection issues should have been taken care of. Ideally such knowledge should be inside ASO. In a way we should not parse ASO messages here.
The fact that Crab Server has to figure out the details of ASO failure and decide on action, means there is too much decisional intelligence in a single place, we have a central see-all-does-all component rather then a modular system. It is a bit against the "CRAB3 design".

When ASO gives up should mean the jobs has to be rerun. Only question is when. In this spirit, given that CrabServer basically knows nothing about site/SE status, downtimes.. full disks, whether user reacts or not, how much buffer is in the system to queue more jobs for this user/destination... I still like the old proposal to treat all ASO failures as fatal, do not resubmit, and bump things in user hand. , basically because we lack the proper feedback and breakers down the line.

In an ideal world, when ASO fails, we should simply rerun the job the usual 3 times. Both full quota and SE down are not a reason not to submit, since we have a large job buffer. And indeed we do not check those before accepting new large submissions, why bother not to resubmit jobs ? Those problems should simply result in transfers slowing/halting, being reported and fixed, while data pile up in /store/temp at various places and is then moved. Expectation being that all those issues like quotas, downtimes e.g. are solved in a few days and we have enough buffer to absorb them. Avoiding a lot of stop and go.
If /store/temp fills up, sites with full buffer should be blacklisted, and if this gets very serious the system grinds to halt to indicate need for drastic actions, with all sort of alarms going off.
But we do not have any knowledge of how those buffers do, so this is not viable, we do not report quota or SE problems other than by/after user noticing failed jobs... and this brings me back to my preferred line:
"we should never retry jobs after ASO fails". As this committ shows, it becomes a game of second-guessing.

Anyhow that was a sort of academic digression, we can't do much better than this commit until we change many things. Maybe a step forward could be a "can write" check before submitting a new task. I never liked the idea in the past, but am changing my mind on that.


The problem is that we do not have good control of the file movements, do not know know how much /store/temp is full, where, by whom, so can not identify real bad cases (send 100k jobs which write to a site down since months) early enough. And end up with raising hands in surrender and hoping users can take a better decision. Of course chances are that they blindly retry and we have gained nothing.

This needs good documentation. In a way I liked the CRAB2 server way to have a table of error-actions which could be modified w/o changing the code.

**Comment by mmascher** [comment]
On Mon, Aug 3, 2015 at 11:29 AM, Stefano Belforte <notifications@github.com>
wrote:

> generally speaking, when jobs are retried, are they simply re-queued in
> condor right away (with priority) or is a delay enforced ?
>

IIRC when jobs are retried they are requeued right away more or less with
an increased priority (in the sense they will run faster), although I can't
find the code to verify that right now.


> @mmascher <https://github.com/mmascher> the question is whether FTS
> retried already. If it did, transient connection issues should have been
> taken care of. Ideally such knowledge should be inside ASO. In a way we
> should not parse ASO messages here.
> The fact that Crab Server has to figure out the details of ASO failure and
> decide on action, means there is too much decisional intelligence in a
> single place, we have a central see-all-does-all component rather then a
> modular system. It is a bit against the "CRAB3 design".
>

About the logic we have in the CRABServer (postjob) the idea has always
been to retry jobs in case of errors in the "source site". But propably ASO
should tell us if we have to retry the job on another place or not..


> When ASO gives up should mean the jobs has to be rerun. Only question is
> when. In this spirit, given that CrabServer basically knows nothing about
> site/SE status, downtimes.. full disks, whether user reacts or not, how
> much buffer is in the system to queue more jobs for this
> user/destination... I still like the old proposal to treat all ASO failures
> as fatal, do not resubmit, and bump things in user hand. , basically
> because we lack the proper feedback and breakers down the line.
>
> In an ideal world, when ASO fails, we should simply rerun the job the
> usual 3 times. Both full quota and SE down are not a reason not to submit,
> since we have a large job buffer. And indeed we do not check those before
> accepting new large submissions, why bother not to resubmit jobs ? Those
> problems should simply result in transfers slowing/halting, being reported
> and fixed, while data pile up in /store/temp at various places and is then
> moved. Expectation being that all those issues like quotas, downtimes e.g.
> are solved in a few days and we have enough buffer to absorb them. Avoiding
> a lot of stop and go.
> If /store/temp fills up, sites with full buffer should be blacklisted, and
> if this gets very serious the system grinds to halt to indicate need for
> drastic actions, with all sort of alarms going off.
>

We are automatically blacklisting sites at submit time[1][2] based on what
the SSB analysis metrics says [3],but that's a slow process and it takes
three days to blacklist a site.

[1]
https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/Recurring/BanDestinationSites.py
[2]
https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/DagmanCreator.py#L553
[3]
https://twiki.cern.ch/twiki/bin/view/CMSPublic/UsableSitesForAnalysis



> But we do not have any knowledge of how those buffers do, so this is not
> viable, we do not report quota or SE problems other than by/after user
> noticing failed jobs... and this brings me back to my preferred line:
> "we should never retry jobs after ASO fails". As this committ shows, it
> becomes a game of second-guessing.
>
> Anyhow that was a sort of academic digression, we can't do much better
> than this commit until we change many things. Maybe a step forward could be
> a "can write" check before submitting a new task. I never liked the idea in
> the past, but am changing my mind on that.
>
> The problem is that we do not have good control of the file movements, do
> not know know how much /store/temp is full, where, by whom, so can not
> identify real bad cases (send 100k jobs which write to a site down since
> months) early enough. And end up with raising hands in surrender and hoping
> users can take a better decision. Of course chances are that they blindly
> retry and we have gained nothing.
>

yeah, if we do not submit users will do and we gain nothing :)


> This needs good documentation. In a way I liked the CRAB2 server way to
> have a table of error-actions which could be modified w/o changing the code.
>

+1

So, apart from this last comment and do the checkwrite at submission time I
fail to see other immediate action item I can turn to github issues. I fear
everything else requires some thinking.

**Comment by belforte** [comment]
I think the only action is to check with the group if anybody sees reasons not to do the checkwrite 
at submission time, then do it. I would do it from the TW, not in the client.

**Comment by juztas** [comment]
+1

2015-08-03 15:26 GMT+02:00 Stefano Belforte <notifications@github.com>:

> I think the only action is to check with the group if anybody sees reasons
> not to do the checkwrite
> at submission time, then do it. I would do it from the TW, not in the
> client.
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmwm/CRABServer/issues/4908#issuecomment-127233099>.
>



-- 
Justas Balcas

**Comment by belforte** [comment]
FYI
resubmissions are given increased priority so that they run before other
jobs from the same user, but not before the famous first 5 jobs in every task.
This is done using priority in the preJob, so it is only valid withing one
schedd. Therefore the prioritization is not perfect, but we avoid global priority
across the pool for user jobs which turned out to be very expensive for negotiator.
relevant code should be in the prejob (IIRC the slack thread).

**Comment by belforte** [comment]
right. But it seems so far we have no indication of ASO being able to
tell us "file on source site went missing". source being down is part
of normal FTS retries (or at least should). Also there's a lot one can say
about lost files vs. disk pools temporary offline. I think in the end
we can't really follow those details at high level, it is fully against
the "PhEDEx approach".
