### ISSUE TITLE
Allow recycling of sanbbox in the crabcache

### ISSUE THREAD

**Issue by mmascher** [dmwm/CRABServer#4948]
Currently each task uploads a different sandbox to the crabcache even if they are they contain the same content. Ther reason is that the code that calculates the checksum [1] includes the timestamps of files.

I propose to change this code and do a real checksum calculation.

PS Note that this checksum is different than the `isbchecksum` I mentioned here [2] which comes from the client and not WMcore[3] and uses MD5 instead of SHA256 (32 vs 64 chars)!

[1] https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/UserFileCache/UserFileCache.py#L85-L97
[2] https://github.com/dmwm/CRABServer/issues/4947
[3] https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/JobType/UserTarball.py#L130-L149

**Comment by belforte** [comment]
you really want to give me haedache !
is the differnce really in how it is computed, or do those checksums refer to different set of files ?
Because using two methods to compute checksum for same stuff really seems too much !
What are the requirements on these checksums ? Why do we care for timestamps to begin with ?
Was a quick&direty alternative to a checksum ? Or fear that checksum may be the same even if
file was changed ?

**Comment by mmascher** [comment]
I am just describing how things are now, I also had an headache when I saw this code :)

We do not definitely need two checksums in my opinion, see also #4947. It's probably just that the crabcache expect a 64 chars checksum, and the other one is used for the `publishname` which expects an Md5 (32 chars) [1]

In other words, there is one checksum which is used for the crabcache sandbox name, and this has nothing to do with the checksum we use for the publication name.

And to complement #4947, the checksum used for the publication name and computed in the client is just a placeholder now. It was there from the CRAB3-Panda era, but then @bbockelm replaced it with the checksum calculated on the worker node with `edmProvDump`. Which AFAIU is the one we should use. In case there is an error or if anything wrong happen then placeholder is used.

[1] https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Lexicon.py#L42

**Comment by mmascher** [comment]
And to finish, in #4947 I am proposing to not bother to calculate the placeholder checksum at all. Here I am simply proposing to improve tha calculation of the other checkusm (for the crabcache) so that identical sandboxes will have identical hash.

**Comment by mmascher** [comment]
These are the three commits I am proposing to take care of this:

Client: https://github.com/mmascher/CRABClient/commit/7e3fbabbf6f1186f092297a44e391f8ddd2ca514
Crabcache: https://github.com/mmascher/CRABServer/commit/e3705c5cf30001d26721d76bfb64fa00d5797ee9
WMCore: https://github.com/mmascher/WMCore/commit/033c6d986eb63797af2fe59357323fe5dee1d27d

However there is one thing we need to discuss. The PSet process object contains a parameter (`_cloneToObjectDict`)[1] that is different every time you import one. This makes the calculation of the checksum different every time, vanishing the purpose of this commit. I solved this by using the original pset instead of the pickle for the checksum calculation, but I am realizing that this is wron as the pickle contains what is really executed runtime (which can be twaked with the py_config_params)

Does anybody know what this is (@Dr15Jones)?

[1] PSet from one submission
```
>>> pprint.pprint(PSet.process._cloneToObjectDict)
{12531088: cms.untracked.PSet(
    input = cms.untracked.int32(10)
),
 14603600: cms.untracked.PSet(
    wantSummary = cms.untracked.bool(True)
),
 14604432: cms.OutputModule("PoolOutputModule",
    outputCommands = cms.untracked.vstring('drop *',
        'keep recoTracks_*_*_*'),
    fileName = cms.untracked.string('outfile.root')
)
,
 14604688: cms.EndPath(output)
}
```

PSet from another submission

```
>>> import PSet
>>> PSet.process._cloneToObjectDict
{15934864: cms.untracked.PSet(
    input = cms.untracked.int32(10)
), 18007376: cms.untracked.PSet(
    wantSummary = cms.untracked.bool(True)
), 18008208: cms.OutputModule("PoolOutputModule",
    outputCommands = cms.untracked.vstring('drop *',
        'keep recoTracks_*_*_*'),
    fileName = cms.untracked.string('outfile.root')
)
, 18008464: cms.EndPath(output)
}
```

**Comment by belforte** [comment]
I am confused. WHat about ignoring this difference and plowing ahead ?
Will the sandbox created for the first submission work with the next ?
that's all that matters. We do not want to create a new sandox and check that
it has same checksum and one which we already stored, we only want to
point to an existing file. You can create any unique ID when you upload the
ISB in the crabcache and remember it. Possibly use it as part of the file name.
Surely I miss something...

**Comment by Dr15Jones** [comment]
The ```_cloneToObjectDict``` is used when objects added to the ```process``` are cloned instead of just referenced. Since the objects are looked up by hash and the hash is dependent on the memory address used by python we have to update ```_cloneToObjectDict``` when we unpickle.

So if you want to checksum a ```Process``` object I'd suggest you either
a) create a special function in Process which calculates one based only on the ```Process``` member data which are invariant across pickling or
b) make a checksum from the string returned by ```process.dumpPython()```.

**Comment by mmascher** [comment]
Hi Chris, thank you! Just for curiosity, do you also know how edmProvDump works?

For Stefano, I think it is a nice property that the id of the sandbox is calulated from its input. It frees you (and the users) from the worry of specifying the id you would like to keep track. Moreover that guarantees that different files in the crabcache will always have different content. I also plan to implement a `--sandbox` parameter for the `crab submit` but imho that's another story.

**Comment by Dr15Jones** [comment]
Hi Marco,

> On Aug 20, 2015, at 8:58 AM, Marco Mascheroni <notifications@github.com> wrote:
> 
> Hi Chris, thank you! Just for curiosity, do you also know how edmProvDump works?

It reads the providence information we store in the EDM ROOT files written by PoolOutputModule. In each file we write all the edm::ParameterSets created from the python configuration for each job that contributed data to the file. We also can access what data each module read for each event.

	Hope that answered your question,

		Chris

Christopher Jones
Fermi National Accelerator Laboratory
cdj@fnal.gov

**Comment by belforte** [comment]
Make sure you include the user's scram directory in the calculation, if
you want an ID which uniquely reflects the "input". E.g. beware the case of
same config but different code.
As all complicated things (and this is complicated IMHO), I think one should
have a solid reasons to do it. All I care for as a user is to have something
to point to one ISB I used before, and I can't see why task name is not good enough.


On 08/20/2015 03:58 PM, Marco Mascheroni wrote:
> Hi Chris, thank you! Just for curiosity, do you also know how edmProvDump works?
>
> For Stefano, I think it is a nice property that the id of the sandbox is calulated from its input.
> It frees you (and the users) from the worry of specifying the id you would like to keep track.
> Moreover that guarantees that different files in the crabcache will always have different content. I
> also plan to implement a |--sandbox| parameter for the |crab submit| but imho that's another story.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmwm/CRABServer/issues/4948#issuecomment-133017540>.
>

-- 
Stefano Belforte - I.N.F.N.     tel   : +39 040 375-6261 (fax: 375-6258)
Area di Ricerca - Padriciano 99 tel mobile: +39 328 010 7327
34012 TRIESTE TS  - Italy       AIM: stefanobelforte

**Comment by belforte** [comment]
I had a brief voice chat with Marco, and finally I understand. Let me try to summarize.
- there's an interesting topic along "do not make a new 100MB tar of the scram project
   if user only changed one cmsRun config parameter". But that's for another time.
- similarly on "do not tar N times in a "multicrab loop" those 100MB when the only
   thing that change from one task to another is the dataset name (common case)".
- here Marco simply wants to keep submission procedure as is, but get a name
   for the ISB that (most of the times) does not change when nothing changes, so that
   at the moment of uploading it, crabcache says "I have it already" and we save on
   transfer and server disk. E.g. there is no attempt to avoid tarring up the
   same 100MB on the client site for every task.
   If sometimes the procedure fails, in the sense that we load twice identical
   stuff with different name... so be it.

So what is being proposed here is OK, including that if every now and then it does
not work and we upload the "same IBS" twice, it is not a problem.
