### ISSUE TITLE
Checksum discussion where and how

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#5034]
So let me summarize here what I would like to see and how things are done now. So far I can tell this is different what PhEDEx is doing, because they have agent on site, which can check file out there and for crab is not the case.

Summary right now:
WN -> /store/temp/ (No checksum)
ASO from /store/temp to final /store/user (No checksum) (ASO uses FTS and FTS uses gfal2)
Client from store/user to working dir (No checksum)
Direct stageout (if WN -> /store/temp fails) (No checksum)

If we save checksum in CRABServer which is calculated on WN:
WN -> /store/temp can enable checksum and calculate locally and see if everything is correct;
ASO -> No possibility without using gfal2. Ignore it? or turn it on?
Direct stageout, we can turn on gfal2 checksum, but not to compare by ourselves on remote destination;
Client to working dir: It can take from crabserver and check checksum after file is copied.

I would prefer:
WN -> /store/temp turn on gfal2, lcgcp, cp checksum which we use from WMCore and also save in CRABServer
ASO -> takes checksum, and provides it to FTS, which in the backend will use gfal-copy -K adler32:checksum or ignore checksum?
Direc stageout: turn on gfal2/lcg-cp checksum, but also compare what CRABServer provided.

So in both cases problems:
a) Ignore ASO checksum (Not preferred by me, but see problems below)
b) Enable ASO checksum (In the end it will still use checksum through gfal2)

Of course there was some problems which I try to catch with storages, gfal2, lcg but as Stefano pointed out not to try to solve all world problems before Christmas :+1: 
Thanks for Caltech, Nebraska, Pisa people for finding these:
https://jira.opensciencegrid.org/browse/SOFTWARE-2006
https://its.cern.ch/jira/browse/DMC-737
https://ggus.eu/index.php?mode=ticket_info&ticket_id=116798 (Pisa - seems to be STORM manager bug that it is not storing adler32 checksum)

**Comment by juztas** [comment]
Also what prod is using on sites which uses lcg-cp, they check checksum with lcg-ls and if it is not provided, they ignore it. Question would be here how much corrupted files happen, see https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Storage/Backends/LCGImpl.py#L171

For gfal2 which is in WMCore, it sets checksum in gfal2 command, which is not yet really used by any site yet, see https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Storage/Backends/GFAL2Impl.py#L71

**Comment by mmascher** [comment]
Hi,

thanks Justas. I'll try to summarize to not get lost in the details.

1) There are several intermediate copy that uses gfal/lcgcp or FTS.
2) Checksum is not enabled when doing these copies[1]
3) Uploading our own checksum to the crabserver solves the problem of the getoutput, but it does not solve the problem entirely as copy done by ASO might be broken (do you confirm @HassenRiahi) 

You are proposing to start relying on lcg/gfal checksums, but that does not seems to work for many sites. AFAIU it might be difficult to check that all the SE softwares (hadoop, storm, dpm, bestman ...) report it correctly to the srm server. And I am not sure a simple ticket to site could solve things as the storage manargeer software developers might be involved.

That said it is a good idea since we cannot always check our own checksum (phedex can since it has an agent running at the site)

[1]  We just turned it on on the client getlog/getout, i.e. we are using -k ADLER32 in the gfal-copy command. But that's just the last step and file might be corrupted before.

**Comment by juztas** [comment]
I am open minded here and as everyone agrees to do that. To check all the SE softwares, it is not limitation, just requires time to work with it and test with all sites. Of course, there is a question which is correct way to do, but as I told, to do same as PhEDEx is not possible in ASO land

**Comment by belforte** [comment]
[I had this in my borwser but forgot to click on it for 2 weeks, anyhow let me recap my thoughts]
I see three different issues:
1. SE to local dir (crab getoutput)
2. ASO
3. direct stageout WN to remote SE

2. should be handed to transfer team, or at least discussed with them
3. so far we plan for this to be only a backup, and in practice did not have issues so far (at least I never saw them being reported), so I am for letting it be
1. AFAIR is the only for which we had some problem report, in very odd cases, where people would get corrupted files sort of one every two copy. Likely serious hardware issues locally, but AFAIK never really understood. For those I would simply read checksum locally and compare with what computed on the WN

Maybe the above is simplicistic, but we have so many things ongoing that I doubt we can properly follow up on all of them. As long as we can make progresses easily, and in the background, OK. But when it comes to raising noise and involving people... let's make sure of our priorities.

**Comment by belforte** [comment]
This is now covered in #5940 We will not implement checksums anywhere else than in FTS/Rucio.
