### ISSUE TITLE
Decrease how long crab3 keeps tasks in the queue

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#5041]
Today 2 biggest schedds were almost filled up. There was several issues and I took some actions to make them space to brief.

To make it not hand work, this is proposal:
a) Change periodic remove from 30d to 20d.
    Details: We are checking entered current status and if task was not resubmitted by user during last 20 days, I would say it is good to delete;
b) Change leave job in queue for successfully finished tasks from 30d to 20d.
    Details: We also check entered current status and if task finished successfully, spool directory is kept for 30d. I don't see a reason to keep it longer than 20d. User might force resubmit, but 20 days to wait is way too much.
c) Rotation of /var/log/secure have to happen more often.
d) HC/HCxrootD is never sending resubmit command. So If HC/HCxrootD task is held (means it is killed/failed), there is no reason to keep spool directory and take space. For log files, it will be the same a and b;

Also this needs to be announced to the users about decreased time of possibility to resubmit.

**Comment by belforte** [comment]
I think you can go ahead with all of that. And also set to 14d instead of 20d (as in last entry in e-log
https://cms-logbook.cern.ch/elog/GlideInWMS/2864
And since we never communicated a policy on this let's not bother to worry users w/o need.
But we really need to enforce an overall time window for a task life inside CRAB, starting from submission day, after a time X (I propose 30d) everything goes. If we want to be nice we can keep around the least possible info for crab report to work for a bit longer, but I do now know what exactly will be needed for that.
It is always the same thing:

Things CAN and WILL go bad. Resubmitting for months is NOT the solution. Users need to take stock of progress after a couple weeks at most and run a smaller recovery task.

**Comment by juztas** [comment]
Thanks for green light. Now everyone is aware of that and I am doing it.

**Comment by belforte** [comment]
np. Please make sure Jadir documents this in the operator twiki pages.

**Comment by juztas** [comment]
He has all commands, I do this only on 2 PM schedds

**Comment by belforte** [comment]
not relevant anymore
