### ISSUE TITLE
Don't apply user whitelist to possible sites when ignore locality is True

### ISSUE THREAD

**Issue by AndresTanasijczuk** [dmwm/CRABServer#5054]
I just realized that in case ignore locality is True we are applying the user site whitelist already to define the "possible sites" in the "site.ad" and "site.ad.json" files: https://github.com/dmwm/CRABServer/blob/3.3.1510.rc9/src/python/TaskWorker/Actions/DagmanCreator.py#L615
This is not consistent with our general approach of applying the user site whitelist (and blacklist) in the pre-job. By applying it already when defining the "possible sites" we are not able to use a different site whitelist in a resubmission.

**Comment by belforte** [comment]
I still think that the Crab2 semantic, where users indicate a list of data locations which override the one from DBS, is better. Easier to understand and use and changes in the code are well localized and do not Interfere with other things. 
Sent from Stefano's mobile

**Comment by belforte** [comment]
in other words: the only reasonable things to handle "ignoreLocation" is to replace what comes from DataDiscovery with the full list of PSN's from SiteDB and then go on with white/blak/ban etc, lists like in normal tasks.
Otherwise we end exactly in this situation where the meaning of "ignoreLocation" is not well defined initially and it gets nailed down as people discuss ad fix holes in the code here and there, in incomplete and inconsistent ways.

**Comment by belforte** [comment]
do I understand correctly that after this commit the user white list will still be appliced, although in the pre-job , not in the TW ?

**Comment by AndresTanasijczuk** [comment]
Yes, that's correct.
