### ISSUE TITLE
ASO database should not be hardcoded to 'asynctransfer'

### ISSUE THREAD

**Issue by juztas** [dmwm/CRABServer#5112]
More details
https://hypernews.cern.ch/HyperNews/CMS/get/crabDevelopment/2464.html
https://hypernews.cern.ch/HyperNews/CMS/get/crabDevelopment/2466/1/1/1.html

**Comment by belforte** [comment]
needed to avoid Couch roration issues again.

**Comment by juztas** [comment]
Also, issue which was got by Diego during validation seems related. he added in crabConfig cmsweb-testbed.cern.ch/couchdb/ and CRAB3 made it cmsweb-testbed.cern.ch/couchdb//asynctransfer/ . This additional '/' I think redirects to different couchdb instance which was validated on preprod by us with Diego. So whenever this change will happen and full url will be inside rest or etc. this should not happen

**Comment by mmascher** [comment]
Note to myself (and on validation time to jadir) about things to check:

* The "publication part" of the crab status (it contacts the aso db and we need to make sure it take the right one)
* Both (1)kill and (2)resubmit connects to the ASO couch db to respectively (1)kill the transfers and (2)the `--resubmit` option of `crab resubmit`
* What happens if I do these commands on "old tasks" (submitted with an old version of REST+TW)?
* I can also foresee a corner case where one submit tasks with an old REST (hence asodb is NULL in the oracle db) but the task is picked up by a new TW

I tried to take care of all these cases in my code and checked the first two bullets for the moment.
