### ISSUE TITLE
CRAB Monitor does not work for (some) schedd at UCSD

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5250]
for example
https://cmsweb.cern.ch/crabserver/ui/task/160622_112204:gsfs_crab_EPOSpPbMinBias816_GEN_SIM_v2

**Comment by emaszs** [comment]
To clarify, the monitor kind of works, just doesn't display the config/pset/scriptexe files because it doesn't find a proxy for the webdir. A proxy should be implemented for these cases, will have to talk with @mmascher to figure it out. Another option would be to get the files using jsonp requests (since they're not subject to cross-domain restrictions), but for that the files should be somehow put into json and the REST interface modified to accept the jsonp requests.

**Comment by mmascher** [comment]
Hi,

UCSD schedd are not behind a firewall and does not need a proxy. There are two APIs, webdir and webdirprx IIRC, what I would do is to use webdirprx and if it does not work use webdir. Can talk more offline.

**Comment by emaszs** [comment]
After some more investigating with @jmarra13 we found that if I want to test this on my VM, port 443 has to be opened to allow UCSD schedds to talk to my REST interface, which in itself seems a very bureaucratic process (https://network.cern.ch/sc/fcgi/sc.fcgi?Action=FirewallRequest&InterfaceName=erupeikatestvm) since it may negatively affect CERN security. 

Will talk with Bruno to see if there are any better options - maybe test this on a preprod crabserver which is already configured correctly.

To address Marco's comment, we talked offline and agreed that a proxy in this case is needed not to get around a firewall but to get past the cross-domain restrictions.

**Comment by emaszs** [comment]
We ran some more tests with Bruno and so far, the proxy mechanism somehow doesn't want to work for UCSD. We set up a proxy to translate the address of a single schedd (submit-6.t2.ucsd.edu) to the cmsweb-testbed.cern.ch domain.
UCSD webdir link:
http://submit-6.t2.ucsd.edu/CSstoragePath/65/uscms4868/160712_070045:jmsilva_crab_HG1607i-rc1-TFile_Analysis_LumiBased-L-T_O-T_P-T_IL-F-DOC-T
"Proxied" webdir link:
https://cmsweb-testbed.cern.ch/CSstoragePath/65/uscms4868/160712_070045:jmsilva_crab_HG1607i-rc1-TFile_Analysis_LumiBased-L-T_O-T_P-T_IL-F-DOC-T

The proxied link fails with 404, we aren't sure why. Bruno said he could consult Diego in this, I'll see how that goes.

**Comment by belforte** [comment]
Marco indicated that UCSD schedd's can be accessed directly w/o the proxy (a couple comments above), 
is that not an option here ?

**Comment by emaszs** [comment]
A proxy in this case is needed not to get around a firewall but to get past the cross-domain restrictions that exist in the browser. IMO, a proxy is the easiest way of doing that.

**Comment by belforte** [comment]
I do not think I really understand (my browser opens happily a webdir at UCSD). Anyhow you clearly 
know better, so I defer. Sorry for the noise.

**Comment by jmarra13** [comment]
The restriction which @emaszs is talking about is described here https://en.wikipedia.org/wiki/Same-origin_policy , basically javascript code only allow downloads from the same domain of the original web page.

**Comment by belforte** [comment]
I would personally be happy with a link to a text page instead
of a downloading into a javascript widget. But if you guys wants to keep it fancy.. up to you.

**Comment by emaszs** [comment]
@belforte There is nothing fancy going on with javascript when loading a file, also, the fix that we tried to implement was very basic, though it didn't work in the end. 

I can modify the link to redirect straight to the text file instead of a tarball (which is the current behavior).

**Comment by belforte** [comment]
for other reasons we are giving up on having schedd's at UCSD.
Closing
