### ISSUE TITLE
use child collector in monitoring script

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5404]
from:  https://cms-logbook.cern.ch/elog/Analysis+Operations/1265
```
Submission Infrastructure asked us to change the collector we talk to when we ask for schedd attributes
(actually the only classads we are interested on). There is a child collector holding those classads and there
is no need to talk to the main collector.

The changes to make in the external configurations are:

cmsgwms-collector-global.cern.ch,cmssrv221.fnal.gov
=>cmsgwms-collector-global.cern.ch:9620,cmssrv221.fnal.gov:9620
```

**Comment by mmascher** [comment]
The other thing we have been asked is to use a projection when querying the collector, see https://github.com/dmwm/CRABServer/commit/7bb427349271ba7022dba0da3499888641a73535

Maybe it is worth using HTCondorLocator in the script? This way we will have to change the code only in one place in the future.

**Comment by belforte** [comment]
I will look into using HTCondorLocator,
but do not understand the protection thing. What is the point exactly there ? GIve a list of needed classAds rather than "everything" ? That list may be different, and there's one already in the script at query time.

**Comment by mmascher** [comment]
It is when you get the classads for building the schedd object, like: https://github.com/dmwm/CRABServer/blob/master/scripts/Monitor/GenerateXMLForTW.py#L178

The version of the python binding we are using on the TW (that comes from the comp builds) is a bit old and `locate` returns the whole list of classads (newer `locate` versions apply the right projection). So, we are forced to use `query` and a projection with the needed attributes to build the schedd object.

Now that I think about it, it might be that if you run GenerateXMLForTW.py as a crontab we are fine since we have a newer version of the python bindings and locate works fine.

**Comment by belforte** [comment]
but in your code you added the list of classAds to a coll.query, not coll.locate.
The coll.query in the script already has the list
https://github.com/dmwm/CRABServer/blob/master/scripts/Monitor/GenerateXMLForTW.py#L81

I have not written this code, so I have no idea of the difference between the two, but if the message is
"use coll.query instead of coll.locate", then I sort of understand.
The crontab runs in the TW environment, so i think it uses same bindings.
But COMP env. should not have obsolete ones.

**Comment by belforte** [comment]
I mean.. we should have proper, uptodate, python bindings in our repo

**Comment by mmascher** [comment]
Yeah, that's for sure. But until this happen my message was: use HTCondorLocator to get the schedd object so that we will only fix one place when the new bindings lands.
