### ISSUE TITLE
malformed URL for webdir in crabserver UI

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5423]
in the crabserver monitor UI like e.g. `https://cmsweb.cern.ch/crabserver/ui/task/170224_082043%3Agminiell_crab_DoubleMuon_Run2016E-23Sep2016-v1_part5_1`
The webdir is pointed to with URL's  like
```
https://cmsweb.cern.ch/scheddmon/0119/cms1943/170306_154025:attikis_crab_JetHT_Run2016B_03Feb2017_ver2_v2_273150_275376
```
I found out that this is not likee by cmsweb redirection rules (at least IIUC) so that when using this from Italy my browser is pointed to a direct URL in e.g. vocm0119 which is firewalled.
Things work instead if I put a `/` at the end of the above URL i.e.
```
https://cmsweb.cern.ch/scheddmon/0119/cms1943/170306_154025:attikis_crab_JetHT_Run2016B_03Feb2017_ver2_v2_273150_275376/
```
I have no idea if this is something to ask Bruno to solve, or if it is better to just add the / in the crabserbver UI

**Comment by emaszs** [comment]
Huh, interesting, had no idea. Bruno added the slash [1], with this redirection should behave as expected without any changes needed from us. We'll test this during validation just in case.

The fix is currently applied to one of the testbed frontends, vocms0135. Another frontend has the old behavior, vocms0134. [2]

[1]
https://github.com/dmwm/deployment/commit/0ac6b93e5e31a0a6561394aa7df328871b7edfde
[2]
https://vocms0135.cern.ch/scheddmon/0119/cms1425 (should work from outside CERN)
https://vocms0134.cern.ch/scheddmon/0119/cms1425 (should not work from outside CERN currently)

**Comment by mmascher** [comment]
If it is any help I discussed something similar in the past with Diego:  https://hypernews.cern.ch/HyperNews/CMS/get/webInterfaces/1360.html

**Comment by emaszs** [comment]
Ah, crap.. thanks @mmascher, this fix doesn't work for files AFAICT. Guess I'll add the slash in crabmon.
