### ISSUE TITLE
Fix crab kill --jobids

### ISSUE THREAD

**Issue by emaszs** [dmwm/CRABServer#5472]
I mentioned one problem with it here, https://github.com/dmwm/CRABServer/issues/5467#issuecomment-293931843, that was easy to fix at least temporarily by converting the ints into strings. However, I'm slightly confused now, the DAG seems to restart the jobs that are removed with crab kill --jobids regardless, (which seemingly does condor_rm for spefic jobids and that is to be expected), how was this not the case previously?

**Comment by emaszs** [comment]
The current situation is that the killed job does not have a job report. RetryJob looks for an exit code, doesn't find it and says it's a recoverable error[1], therefore the killed job gets resubmitted automatically. If we were to say that a missing job report is an unrecoverable error (return 2 instead of 1 [1]), it would fix the `kill --jobids` command but I'm not sure what other implications this has.

Alternatively we could maybe rely on status2 to determine if the job has been actually killed but to me it seems like a big change at the moment.

[1] https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/RetryJob.py#L285

**Comment by belforte** [comment]
there may be a way to find out that job was killed intentionally
w/o making assumptoins based on lack of job report (which may indeed
be recoverable). I will have a look.

**Comment by belforte** [comment]
but I wonder what may have changed in last months here. This sounds like it should have never worked

**Comment by belforte** [comment]
@dciangot and myself dissected a bit the crab kill flow in order to understand how to kill transfers in ASO in the proper way. As a side discovery, we think that the problem with `crab kill --jobids` may be in this line which is the only thing which makes the action different from what done in case of `crab kill` w/o arguments
https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/DagmanKiller.py#L78
which was inserted via
https://github.com/dmwm/CRABServer/commit/d53dfd7cea522229b56249d571e9e53fc10f2670

**Comment by belforte** [comment]
@dciangot suggest that the second `&&` in that line should rather be a `||` (OR, not AND !)

**Comment by emaszs** [comment]
@belforte This is only a constraint expression for which jobs to kill, I doubt it has anything to do with the real issue. I reported that this expression is broken in the first issue comment [1], however it's broken for a different reason than you and @dciangot found and it's easy to fix. IMO the constrain in no way affects what happens to the jobs **after** they are removed with a condor_rm, which is where the real problem is.

[1] https://github.com/dmwm/CRABServer/issues/5472#issue-223770153

**Comment by belforte** [comment]
OK. So the constrain expression does not select any job now and this is likely due to at least TWO problems, the need to add quotes around jobids that you spotted and the && which Diego spotted, since parent_ID is only available when using automatic splitting.
Then we still have to investigate what happens when jobs are removed.
I will follow up on that.

**Comment by emaszs** [comment]
@belforte I'm certain that the parent_ID is not causing issues in the current constraint expression, it's only the quotes around the job ids. I think the parent_id is simply the job id if automatic splitting is not enabled, in which case it works just fine once you fix the quotes.

Anyhow, I've spent a significant amount of time debugging this and checking diffs between commits in the last year or so (mostly autosplitting), and while it is interesting, I didn't make much progress unfortunately - it seems to me like this feature is not part of the overall design in the PostJob. I'm hesitant to start implementing this from scratch due to various corner cases that come up, though maybe it's not hard at all, have to try doing it first. If you can spot or recall something it would be great of course.

**Comment by belforte** [comment]
@emaszs OK. Indeed looking at currently running jobs ` CRAB_ParentId` is set and the same as `CRAB_Id`
I would have sweared that we had seen  ` CRAB_ParentId`  to be missing, but clearly we must have been confused.
Let's not rush to do anything here. We also had a discussion about a related topic last friday with Diego, Marco and myself and we find more and more that individual job kill+resubmit is becoming more dangerous than useful. Let's make sure we have well clear what we really need before we implement one thing or another.
We clearly suffer of lack of documentation :-(
https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3Commands#crab_kill

**Comment by belforte** [comment]
I took advantage of yesterday's mega kill to look at the effect of resubmit and indeed at least some killed (condor_rm'ed) jobs had the postjob complain about exited with error and resubmitting [*]
I am sure it is easy to solve. But the big questions remain:
1. what do we want to happen ?
2. what does it mean "crab kill" and/or "crab kill --jobid ..." ?
3. is there a use case for crab hold instead ?

[*]
so job was killed via condor_rm after a condor_hold of the dag, and pj did not run.
Then one issues crab submit (in this case I issued condor_release by hand) and the PJ runs, here's its log
```
belforte@vocms0195/cluster7720944.proc0.subproc0> cat postjob.1279.1.txt
Thu, 25 May 2017 22:58:23 CEST(+0000):INFO:PostJob ======== Starting execution. Task Worker Version 3.3.1705.rc3.jemalloc
Thu, 25 May 2017 22:58:23 CEST(+0000):DEBUG:PostJob Creating symbolic link in task web directory to post-job log file: /home/grid/cms1042/170521_101612:dsalerno_crab_JetHT-Run2016G-03Feb2017-v1_V25_systematics_nBCSVM_CR_v1/postjob.1279.1.txt -> postjob.1279.1.txt
Thu, 25 May 2017 22:58:23 CEST(+0000):DEBUG:PostJob Copying job report from jobReport.json.1279 to job_fjr.1279.1.json.
Thu, 25 May 2017 22:58:23 CEST(+0000):DEBUG:PostJob Creating symbolic link in task web directory to job report file: /home/grid/cms1042/170521_101612:dsalerno_crab_JetHT-Run2016G-03Feb2017-v1_V25_systematics_nBCSVM_CR_v1/job_fjr.1279.1.json -> job_fjr.1279.1.json
Thu, 25 May 2017 22:58:23 CEST(+0000):INFO:PostJob This is job retry number 1. The maximum allowed number of retries is 2.
Thu, 25 May 2017 22:58:23 CEST(+0000):DEBUG:PostJob This post-job corresponds to job with Condor ID 7842060.
Thu, 25 May 2017 22:58:23 CEST(+0000):INFO:PostJob ====== Starting to parse job ad file /data/srv/glidecondor/condor_local/job_history/history.7842060.0.
Thu, 25 May 2017 22:58:23 CEST(+0000):INFO:PostJob        -----> Started 0 time out of 5 -----
Thu, 25 May 2017 22:58:23 CEST(+0000):INFO:PostJob        -----> Succeeded to parse job ad file -----
Thu, 25 May 2017 22:58:23 CEST(+0000):INFO:PostJob        -----> Succeeded to copy job ad file.
Thu, 25 May 2017 22:58:23 CEST(+0000):INFO:PostJob ====== Finished to parse job ad.
Thu, 25 May 2017 22:58:23 CEST(+0000):INFO:PostJob ====== Starting to analyze job exit status.
Thu, 25 May 2017 22:58:23 CEST(+0000):INFO:PostJob        -----> RetryJob log start -----
Thu, 25 May 2017 22:58:23 CEST(+0000):DEBUG:RetryJob Job ads already present. Will not use condor_q, but will load previous jobs ads.
Thu, 25 May 2017 22:58:23 CEST(+0000):INFO:RetryJob Job and stageout wrappers finished successfully (exit code 0).
Thu, 25 May 2017 22:58:23 CEST(+0000):ERROR:RetryJob Payload job was successful, but wrapper exited with non-zero status -1002
Thu, 25 May 2017 22:58:23 CEST(+0000):INFO:PostJob        <----- RetryJob log finish ----
Thu, 25 May 2017 22:58:23 CEST(+0000):INFO:PostJob The retry handler indicated this was a recoverable error. DAGMan will retry.
```

the `bad` line is
```
Thu, 25 May 2017 22:58:23 CEST(+0000):ERROR:RetryJob Payload job was successful, but wrapper exited with non-zero status -1002
```
which makes no bloody sense since as the log says
```
This post-job corresponds to job with Condor ID 7842060
```
and:
```
condor_history 7842060 -userlog job_log -af jobstatus -af RemoveReason
3 via condor_rm (by user condor)
```
jobstatus 3 means X = removed.

How PJ could have decided that application was OK, beats me, but it is possible that this happens since the time HTCondor started reporting job stdout also for killed jobs (at our request to have it for jobs which hit walltime or memory limit) and the PJ uses the presence of the file, rather than the condor ads, as a way to tell job status.

So I think it is fixable

**Comment by belforte** [comment]
and of course the `RemoveReason = "via condor_rm (by user condor)"` is present also in the file that the PJ says it parses `/data/srv/glidecondor/condor_local/job_history/history.7842060.0`

**Comment by belforte** [comment]
in the end it seems that the PostJob code (e.g. in here
https://github.com/dmwm/CRABServer/blob/master/src/python/TaskWorker/Actions/PostJob.py#L1510-L1520
) fails to detect this case as described in the condor manual the code refers to
http://research.cs.wisc.edu/htcondor/manual/v8.2/2_10DAGMan_Applications.html

```
 A job that dies due to a signal is reported with a $RETURN value representing the additive inverse of the signal number. For example, SIGKILL (signal 9) is reported as -9. A job whose batch system submission fails is reported as -1001. A job that is externally removed from the batch system queue (by something other than condor_dagman) is reported as -1002. 1004
```
and somehow manages to plow on as if the job succeeded...

**Comment by belforte** [comment]
In CRAB Meeting on MAy 30 we decided to deprecate crab kill --jobId
see:
https://indico.cern.ch/event/640918/note/
