### ISSUE TITLE
Make sure that Task Process runs for 1 day after CRAB_TaskEndTime

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5509]
see https://github.com/dmwm/CRABServer/issues/4681#issuecomment-307109907
and https://indico.cern.ch/event/640918/note/

**Comment by emaszs** [comment]
I'm not sure if something needs to be changed here. If the DAG is put on hold because it had reached `CRAB_TaskEndTime`, the task process will wait for at least a day before exiting. It won't exit exactly at `CRAB_TaskEndTime + 1 day`, but it should be close, because every 5 minutes it will be checking if the task has been in hold status for a day. So I guess it should not run for longer than  `CRAB_TaskEndTime + 1 day + 5 minutes`.

**Comment by belforte** [comment]
the idea was to make sure that it is 1 day, not 2 or more. 5min of course do not matter. If you are sure it is 1 day, close. Thanks
