### ISSUE TITLE
Database passwordchange before 27-03-2018

### ISSUE THREAD

**Issue by todor-ivanov** [dmwm/CRABServer#5655]
To change the database password for the 'prod' account: 'cms_analysis_reqmgr' before 27-03-2018

**Comment by belforte** [comment]
Neat. How are those reader and writer accounts authorized the if not via password? sent from Stefano's mobileOn Mar 13, 2018 2:46 PM, Marco Mascheroni <notifications@github.com> wrote:Notice that the production instance of the CRAB3 REST, the one on cmsweb, does not use the cms_analysis_reqmgr account, but the associated reader and writer accounts. So for this you only need to update your scripts and notify people who has the old pwd. This is to prevent the account to get locked because of wrong pwd entered.

**Comment by mmascher** [comment]
They have their own passwords (for a total of 3). We do not receive mandatory notifications to change them,

**Comment by belforte** [comment]
Todor says that he had done it.

**Comment by todor-ivanov** [comment]
I may confirm the password has been changed on 13.03.2018
