### ISSUE TITLE
TapeRecall recurring action should touch sandbox

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5727]
user sandbox in crab cache is deleted 3 days after written, as per
https://github.com/dmwm/deployment/blob/master/crabcache/deploy#L22

But tape recall can take longer and we need to make sure that
the sandbox will still be there when task is sent to TW for submissioni again.

The idea is to look into using this API to try to upload again the same file
https://github.com/dmwm/CRABServer/blob/631c55d6cc9f5aae1c73085b1e38051d00a4494c/src/python/UserFileCache/RESTFile.py#L85
Looks like adummy file will do as long as the hashkey is correct,
if file is already there no transfer will be attempted and file on cache disk will be touch'ed.

This needs to be done with the user proxy siince crabcache put files on disk
in a directory named after the user and the path is resolved inside the API,
can not be passed externally.

**Comment by belforte** [comment]
adding here so it doesn't get lost some hints after trying out a few things with @lecriste 
cracache API can't be called that easily, we need to make a REST call which mimics crab submit sandbox upload, which is code we are not familiar with, something along the lines of
```
from WMCore.Services.UserFileCache.UserFileCache import UserFileCache
filecacheurl='https://stefanovm2.cern.ch/crabcache'
ufc=UserFileCache({'endpoint' : filecacheurl, "pycurl": True})
result = ufc.upload(archiveName)
```
But I did not try to really make that work.

I  tried a simple `curl -X PUT ...` but could not find the proper incantation, nor we have example from REST logs (where it is only reported that `cmsweb.cern.ch/crabcache/file` has been contacted).

One could look at how CRAB Cient uploads the log file, code is simpler there.

A more appealing possibility is to use the fact that sandbox file is touched also when it is retrieved with a GET

curl -X GET -key $X509_USER_PROXY --cert $X509_USER_PROXY -k  'https://stefanovm2.cern.ch/crabcache/file?hashkey=807c13af268a3d10a521a05ba24d3c0c1371415c727f3c7f936a72408030745f' > /dev/null 
indeed I verified that this works for my VM (i.e. updates the file date shown with `ls /data/srv/state/crabcache/b/belforte/*` ):
```
curl -X GET -key $X509_USER_PROXY --cert $X509_USER_PROXY -k  'https://stefanovm2.cern.ch/crabcache/file?hashkey=807c13af268a3d10a521a05ba24d3c0c1371415c727f3c7f936a72408030745f' > /dev/null 
```

**Comment by lecriste** [comment]
The sandbox path in the CRAB cache is of the type
`/data/srv/state/crabcache/files/l/<username>/<hashkey>`

and the UserFileCache "upload"/"download" methods require only the `hashkey` as input.
The `username` is taken from the DN-username map in
`/data/srv/state/frontend/etc/authmap.json`

so the TW fails to touch the sandbox because its DN is not mapped to the `username` in the sandbox path.

**Comment by mmascher** [comment]
Not sure how things are gonna be handled in CRIC, but in SiteDB if you specify the CRAB3 operator role you should be able to access other people sandboxes.

**Comment by belforte** [comment]
nothing to do with CRIC, CRAB gets roles from CMSWEB frontend, which will keep proviging them either via SiteDB or CRIC transparently to us.
But the tape recall action has access to the user DN, IIUC it is used to send the request to Dynamo, so it should be possible to use it to touch the sandbox.

**Comment by belforte** [comment]
weel.. IIUC the request to Dynamo is sent with the TW credential, but has the user DN among the data.

**Comment by mmascher** [comment]
Right, but are role gonna be preserved with the CRIC transition?

**Comment by lecriste** [comment]
The request to Dynamo does not contain the user DN.
The tape recall action has access to the task dictionary and so to the user DN.

Apart from the potential authentication issue, the problem is that, in order to get the [sandbox path](https://github.com/dmwm/CRABServer/issues/5727#issuecomment-423379470), the current WMCore/UserFileCache calls [this function](https://github.com/dmwm/CRABServer/blob/631c55d6cc9f5aae1c73085b1e38051d00a4494c/src/python/UserFileCache/RESTFile.py#L38) that looks for the request DN in the authmap.json file and picks up the username mapped to it (`cherrypy.request.user['login']`).
In principle we can avoid using the DN-username mapping by making use of the `username` [argument](https://github.com/dmwm/CRABServer/blob/631c55d6cc9f5aae1c73085b1e38051d00a4494c/src/python/UserFileCache/RESTFile.py#L34), how can we specify it [here](https://github.com/dmwm/CRABServer/blob/631c55d6cc9f5aae1c73085b1e38051d00a4494c/src/python/UserFileCache/RESTFile.py#L101) starting from [this call](https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/UserFileCache/UserFileCache.py#L125)?

**Comment by mmascher** [comment]
Can you try to modify WMCore ath this line

https://github.com/dmwm/WMCore/blob/master/src/python/WMCore/Services/UserFileCache/UserFileCache.py#L129

by adding &username=whatever ?

IT should work

**Comment by lecriste** [comment]
Yes, it works:

https://github.com/dmwm/CRABServer/pull/5728#issuecomment-423628068

**Comment by belforte** [comment]
will that mean allowing anybody to overwrite anybody's else sandbox ?

**Comment by belforte** [comment]
you can look at new509env (in ServerUtilities) for the env.switching

I thought you logged somewhere in dynamo the DN of the user who makes
the request, anyhow...

that is exactly how the frontend/backend communication is supposed to work
in production, what is the problem with that ?

**Comment by lecriste** [comment]
> will that mean allowing anybody to overwrite anybody's else sandbox ?

No, four three reasons:
1. I am downloading the sandbox, not uploading
2. and using the task username:
https://github.com/dmwm/CRABServer/pull/5728/commits/fb73371d47a978023b26380350064b69ede22f99#diff-2e009b0dc14eee5a505e9a511172c646R35

3. As Marco [said](https://github.com/dmwm/CRABServer/issues/5727#issuecomment-423440580), only user with "operator" role in the "crab3" group are allowed to access other people sandboxes.

**Comment by belforte** [comment]
Ok. Thanks. Let's always make a little effort to clearly document what we do in the code for long term maintenance. Crab at large is not great on this. Let's take any chance to improve sent from Stefano's mobile

**Comment by lecriste** [comment]
This FAQ states "5 days":
https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRAB3FAQ#User_quota_in_the_CRAB_cache

instead of 3:
https://github.com/dmwm/deployment/blob/master/crabcache/deploy#L22

@belforte, is there any other piece of code executing such cleaning?

**Comment by belforte** [comment]
no other place that I know of. Of course it is difficult to be sure that "nothing exist". It may be worth to check with Lina, since we can't log on the crabcache production machine to verify that they do not run something else/different.

**Comment by lecriste** [comment]
Depending on the environment (`X509_USER_*`), the touch of the task sandbox may fail.
