### ISSUE TITLE
ASOWorker hardcoded to 'asoprod1' for direct stageout

### ISSUE THREAD

**Issue by dciangot** [dmwm/CRABServer#5835]
@belforte @lecriste
See:
http://dashb-cms-job.cern.ch/dashboard/templates/task-analysis/#user=kwei&refresh=0&table=Jobs&p=1&records=25&activemenu=2&status=&site=&tid=190304_202134%3Akwei_crab_AMSB_chargino1000GeV_ctau10000cm_step1

In case of direct stageout we need to change the default value of  asoworker to 'asoless'

**Comment by lecriste** [comment]
+1

**Comment by belforte** [comment]
there's no `asoprod1` string in CRAB code base. We need to find out how this gets put in the DB !

**Comment by belforte** [comment]
I looked at some random jobs in that task, and all staged locally.
Can you point to the example of direct stageout ? thanks.

**Comment by dciangot** [comment]
AcquirePublication_sql query is doing it on part of jobs that are directly staged (e.g. Having the aso worker field Null). It's a safe race, but it is a race for that kind of jobs between the 2 publishers we are running. 

https://github.com/dmwm/CRABServer/blob/master/src/python/Databases/FileTransfersDB/Oracle/FileTransfers/FileTransfers.py

**Comment by belforte** [comment]
Gotcha. Given that we will turn off one of those publishers soon... Do we need to fix this? sent from Stefano's mobileOn Mar 5, 2019 18:24, dciangot <notifications@github.com> wrote:AcquirePublication_sql query is doing it on part of jobs that are directly staged (e.g. Having the aso worker field Null). It's a safe race, but it is a race for that kind of jobs between the 2 publishers we are running.
https://github.com/dmwm/CRABServer/blob/master/src/python/Databases/FileTransfersDB/Oracle/FileTransfers/FileTransfers.py

**Comment by dciangot** [comment]
probably not, just closing this and I'll re-open if something won't go as expected.

**Comment by belforte** [comment]
BTW it came to my mind that setting asoworker name inside the PostJob (which is what would be required here) is exactly what we wanted to do to avoid ASO xfer race conditions and did not do because it requires a new query in CRAB REST. May we overlooked some obvious solution for month and this is actually easy... but can't be confident about it. So we better not need this.

**Comment by belforte** [comment]
BTW it came to my mind that setting asoworker name inside the PostJob (which is what would be required here) is exactly what we wanted to do to avoid ASO xfer race conditions and did not do because it requires a new query in CRAB REST. May we overlooked some obvious solution for month and this is actually easy... but can't be confident about it. So we better not need this.
