### ISSUE TITLE
crabID should be a number

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5860]
now it is a string to accomodate automatic splitting numberingof probes as 0-1 ... 0-5
and tails as 30-1...30-99 etc.
But for proper sorting in Grafana we need a number

**Comment by lecriste** [comment]
Since CRAB code is full of such condition looking for the Automatic splitting `-` symbol in the job number:
https://github.com/dmwm/CRABClient/blob/master/src/python/CRABClient/Commands/status.py#L542

I propose to convert the current string to a number only in the Benjamin script:
https://github.com/dmwm/cms-htcondor-es/blob/master/src/htcondor_es/convert_to_json.py#L30

@belforte if you agree I will create an issue there and follow up with Christian to understand which is the best conversion for Grafana.

**Comment by belforte** [comment]
Good idea Leo. makes a lot of sense to me.
Let's make sure that @stiegerb also likes it  and then we go. I meet with Christian on monday morning, can surely ask about this.

**Comment by stiegerb** [comment]
We just changed CRAB_Id to be treated as a string, so I would suggest to just create a new field that can be used for sorting.

But I don't fully understand the problem. This is about sorting entries in a table in Grafana? It can't do that with a string?

**Comment by belforte** [comment]
yes to both

**Comment by lecriste** [comment]
Closed via https://github.com/dmwm/cms-htcondor-es/pull/34/files

**Comment by belforte** [comment]
@lecriste that does not look like the correct reference

**Comment by lecriste** [comment]
Moved to https://github.com/dmwm/cms-htcondor-es/issues/118
