### ISSUE TITLE
Probe Jobs output should not be transferred

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5918]
We are getting reports from users of tasks with automatic splitting where all probe jobs are failed (after 3 retries) because the postjob fail in ASO step.
Usually because no output file was produced. Which may be OK for jobs which are terminated after a few mins, even if the probe job completed with exit code 0.
Butt here is no point in staging out the output of probe jobs and AFAIR it is not supposed to happen.
Needs investigating.
Recent example:
https://cmsweb.cern.ch/crabserver/ui/task/190720_173043%3Asnorberg_crab_SMS-T2cc_genHT-160_genMET-80_fastSim_2018

**Comment by lecriste** [comment]
Removing the recently introduced `LeaveJobInQueue` [attribute](https://github.com/dmwm/CRABServer/commit/48b3700c0f0feaf273f1ae766e53da61edcf0b6c#diff-87c8bab9e7cf28a8e8b0526de0cbed82) hides the bug: 
https://cmsweb-testbed.cern.ch/crabserver/ui/task/190730_101154%3Alecriste_crab_AutomaticSplitt_data_preprod_noLeaveJobInQueue_highP

**Comment by lecriste** [comment]
The value of the `CRAB_TransferOutputs` attribute in the so-called [ROOT job ad file](https://github.com/dmwm/CRABServer/blob/ecb1de3774e919aef044b942b252d81b77e05116/src/python/TaskWorker/Actions/PostJob.py#L1830) is wrong for probe jobs. It should be `0`, as correctly set in the Condor job ClassAd, instead of `1`.

With the recently introduced LeaveJobInQueue attribute [expression](https://github.com/dmwm/CRABServer/blob/ecb1de3774e919aef044b942b252d81b77e05116/src/python/TaskWorker/Actions/DagmanCreator.py#L139), the [job "history" file](https://github.com/dmwm/CRABServer/blob/ecb1de3774e919aef044b942b252d81b77e05116/src/python/TaskWorker/Actions/PostJob.py#L1797) does not exist yet [at this moment](https://github.com/dmwm/CRABServer/blob/ecb1de3774e919aef044b942b252d81b77e05116/src/python/TaskWorker/Actions/PostJob.py#L1802) and so PostJob fetches the job ad from the [ROOT job ad](https://github.com/dmwm/CRABServer/blob/ecb1de3774e919aef044b942b252d81b77e05116/src/python/TaskWorker/Actions/PostJob.py#L1790) (we should also fix this fetching order as the job "history" file is no longer existing at PostJob runtime).

**Comment by belforte** [comment]
Bravo! sent from Stefano's mobileOn Jul 31, 2019 17:08, Leonardo Cristella <notifications@github.com> wrote:The value of the CRAB_TransferOutputs attribute in the so-called ROOT job ad file is wrong for probe jobs. It should be 0, as correctly set in the Condor job ClassAd, instead of 1.
With the recently introduced LeaveJobInQueue attribute expression, the job "history" file does not exist yet at this moment and so PostJob fetches the job ad from the ROOT job ad (we should also fix this fetching order as the job "history" file is no longer existing at PostJob runtime).

**Comment by lecriste** [comment]
Probably all we need is to replicate this codition:
https://github.com/dmwm/CRABServer/blob/ecb1de3774e919aef044b942b252d81b77e05116/src/python/TaskWorker/Actions/PreJob.py#L332

in this line:
https://github.com/dmwm/CRABServer/blob/67c45b2bfcf650e1e2f4f086fa88a9f23e20d3e9/src/python/TaskWorker/Actions/DagmanSubmitter.py#L59

@belforte do you agree?

**Comment by lecriste** [comment]
In the DagmanSubmitter we can not differentiate between probe and non-probe
jobs.
I added a protection in the PostJob which seems the safest way.
