### ISSUE TITLE
verify when/how task_process is running

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#5924]
As @mmascher wrote:
```
Also Stefano, I am blinking on the architecture of the task process, is it supposed to stay around 30 days (task lifetime), or is it exiting once a task is completed (and restarted in case of resubmit)? 
```

**Comment by belforte** [comment]
for reference. The "design" of how it should work is here:
https://github.com/dmwm/CRABServer/issues/4681#issuecomment-302336451

It is  a long issue, but I think that we converged on "task_process runs from initial submission until task lifetime expires".

**Comment by belforte** [comment]
After checking the code, I came to the conclusion that task_proc_wrapper is started when the DAGMAN is initially launched by `dag_bootstrap_startup.sh` and stops 24 hours after the DAG has stopped to run. It the DAG is restarted by a resubmit, the cycle will repeat.

https://github.com/dmwm/CRABServer/blob/c33576ee261a32fd0c076cb95f2db50c48a50aaf/scripts/task_process/task_proc_wrapper.sh#L140-L147

**Comment by mmascher** [comment]
Thanks for checking this Stefano. I seemed to remember as well it was running for 24 hours after the dag was in a final state. I was asking because I saw some task processes running weeks after the dag was submitted, and the dag was in a completed state. But I do not remember if I checked when the DAG stopped.. It's probably a false alarm, but something to keep an eye on.
