### ISSUE TITLE
CRAB submssion failing because one HA collector not responding

### ISSUE THREAD

**Issue by lecriste** [dmwm/CRABServer#5932]
From https://cms-logbook.cern.ch/elog/Analysis+Operations/2769

At times the query to collector to get list of schedd fails. At the moment the API simply queries one collector at random between the two (CERN and FNAL).
Maybe collector name at FNAL changed and we did not follow ?
Otherwise we (or Madison) may have to change the code to be robust against one of the two HA collector not responding.

**Comment by belforte** [comment]
actually here it was not as much one collector not responding (being down) as not returning the expected information. With day after wisdom I do not know if the API can do any better.
@bbockelm any guidance ?

**Comment by aperezca** [comment]
The backup central manager for the global pool at FNAL is being moved to a new host. This is happening during a transition period, until the majority of the pool is formed by pilots contacting the new host, when we did the switch. New collector host name was updated in all centrally managed schedds days ago. In the transition, as the old collector is still on, it may provide old stale information, which is the origin of the issue here, I think. 
My question though is why is the main collector not being queried preferentially? Load balancing?

**Comment by belforte** [comment]
everything understood. Thanks Antonio. I will explain in e-log

**Comment by belforte** [comment]
as for this isssue, the only thing we can do is a sanity check and raise an error if query to collector returns an empty list.
