### ISSUE TITLE
Report failure message when Automatic splitting fails

### ISSUE THREAD

**Issue by lecriste** [dmwm/CRABServer#5983]
E.g.:
https://hypernews.cern.ch/HyperNews/CMS/get/crabFeedback/8492/1/1.html

Using [failTask](https://github.com/dmwm/CRABServer/blob/a4aa634d241a0a3f157f1199118ae983b8efb996/src/python/TaskWorker/Worker.py#L41) [here](https://github.com/dmwm/CRABServer/blob/9e8efac5974ae2fd4086e3218b83ea4dafbbf87f/src/python/TaskWorker/Actions/PreDAG.py#L250) should do.

**Comment by belforte** [comment]
looks perfect. Let's make sure it works :-)
we may still want to change a bit what crab status prints to make it clear what the pointed-to predag log file is.

**Comment by belforte** [comment]
see https://cms-talk.web.cern.ch/t/a-portion-of-the-events-not-submitted-with-crab/17537/7
I do not want to spend hours again looking at logs and files only to re-discover this.

Marking it as available even if assigned to me so that @novicecpp or @mapellidario can pick it up if interested. Change should be simple.

**Comment by novicecpp** [comment]
I do not remember why I am open this again (maybe wait for deploy in production).
Closing.
