### ISSUE TITLE
ArgumentError exception in PreJob

### ISSUE THREAD

**Issue by lecriste** [dmwm/CRABServer#6106]
All jobs of [this task](https://cmsweb.cern.ch/crabserver/ui/task/200728_204332%3Atodiotal_crab_CMSDAS_MC_generation_test0) failed at preJob with

```
Traceback (most recent call last):
  File "TaskWorker/Actions/PreJob.py", line 563, in execute
    self.alter_submit(crab_retry)
  File "TaskWorker/Actions/PreJob.py", line 367, in alter_submit
    new_submit_text += '+CMSGroups = %s\n' % classad.quote(self.task_ad['CMSGroups'])
ArgumentError: Python argument types in
    classad.quote(Value)
did not match C++ signature:
    quote(std::string)
```
https://cmsweb.cern.ch/scheddmon/0194/cms871/200728_204332:todiotal_crab_CMSDAS_MC_generation_test0/SPOOL_DIR/prejob_logs/prejob.1.0.txt

**Comment by lecriste** [comment]
The user was using an old cfg template with
`from WMCore.Configuration import Configuration
`
instead of
`from CRABClient.UserUtilities import config
`

and the error does not occur with the new `import`.

**Comment by belforte** [comment]
interesting. I was not aware of such difference. It is quite bad that errors appear in PreJob which is the most hidden and hardest to debug. I will see what can be done. But am keeping at low priority.

**Comment by belforte** [comment]
I can't believe that the problem was due to 
` from WMCore.Configuration import Configuration `
since `CRABClient.UserUtilities.config` simply calls that.

Also I have no idea how the submission configuration may affect the PreJob. 

More likely the error is due to ` CMSGroups = undefined; ` in `adjust_out.txt`

For a normal job this classAd is set to e.g .`CMSGroups = "/cms"`

we have this problem with missing CMSgroup at some point due to lack of CVMFS in TaskWorker.  SO maybe this time there was a glitch which made CVMFS unaccessible and caused the error. In the TW log for this task I find:
```
2020-07-28 22:43:45,319:DEBUG:DagmanCreator:{'tempDir': u'/data/srv/tmp/_200728_204332:todiotal_crab
_CMSDAS_MC_generation_test06mTWNa' [...] 'user_groups': set([]) ...
```
and
```
2020-07-28 22:44:43,160:INFO:DagmanSubmitter:User todiotal mapped to local groups set([]).
```
So will handle this like a missing check in TW which should have lead to failed submission

**Comment by belforte** [comment]
looking a the code, the CVMFS problem would have caused a different failure, the only way to get the reported error is that the default `/cms` VOMS group is not found in the user proxy here
https://github.com/dmwm/CRABServer/blob/e1ff8a5a0387cf5840b6d8f12c6ec40c5cec777f/src/python/TaskWorker/Actions/MyProxyLogon.py#L36
which is indeed "incredible".
oh well... let's just make sure that when at DAG submission time the group set is not empty
https://github.com/dmwm/CRABServer/blob/e1ff8a5a0387cf5840b6d8f12c6ec40c5cec777f/src/python/TaskWorker/Actions/DagmanSubmitter.py#L425-L426
which is where the problem was reported in the log:
```
2020-07-28 22:44:43,160:INFO:DagmanSubmitter:User todiotal mapped to local groups set([]).
```

**Comment by lecriste** [comment]
One more case:
https://cmsweb.cern.ch/crabserver/ui/task/200730_171102%3Avwachira_crab_CMSDAS_MC_generation_test0

These are ~new CMS users running a tutorial for the CMSDAS.

**Comment by belforte** [comment]
I see that the user resubmitted the same task today and it did work
https://cmsweb.cern.ch/crabserver/ui/task/200731_064649%3Avwachira_crab_CMSDAS_MC_generation_test0
we seem to have some intermittent problem with VOMS ??? Hopefully the changes in https://github.com/belforte/CRABServer/commit/214e7d59df769607774d7da96d45b8a133c5c829  will help to nail things.

**Comment by belforte** [comment]
I   serendipitously  found the actual reason for this problem.
Due to a small mistake on my side in recent changes, myproxy delegation in TaskWorker results in undefined usergroups just only for the first taks of a first-time user.
In this code `usergroups` should only be defined in after the proxy delegation was successful, otherwise it is set to empy since there is proxy to begin with, and then a proxy is created and TW goes on submitting the task. Basically `usergroups=...` at line 36 should be moved to right before the final `return`

https://github.com/dmwm/CRABServer/blob/a78ed1ce25d3b8873419ca259e60467c5a4277ce/src/python/TaskWorker/Actions/MyProxyLogon.py#L21-L50

**Comment by lecriste** [comment]
@Martijn Mulders <martijn.mulders@cern.ch>, first benefit of the
CMSDAS@CERN2020 :)
