### ISSUE TITLE
test latest WMCore 1.3.6

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6108]
IIUC correctly (to be verified! ) the latest stable WMCore version is 1.3.6 before they started changing things for Python3 compatibility. So we shoudl build with 1.3.6., validate, and use in production until ready to deal wityh py3 transition or anyhow having more news from Alan.

**Comment by amaltaro** [comment]
That's correct, Stefano. Starting in >= 1.3.7.preX, we have the futurize fixes:
https://raw.githubusercontent.com/dmwm/WMCore/master/CHANGES

**Comment by belforte** [comment]
Generally speaking, should we expect that we can run current CRAB code with futurized WMCore, or should better stick with 1.,3.6_crab branch until we make some largish changes to CRAB code ?

**Comment by belforte** [comment]
answering my previous comment:
we should stay with 1.3.6.crab1 and do all pending work. Than look at integrating py2/3 changes later this fall.
@ddaina were are we on testing with 1.3.6 ?

**Comment by ddaina** [comment]
TW was deployed with `1.3.6` and tested. Today I deployed it using `1.3.6.crab1`. `crabserver` and `crabcache` are still untouched, i.e uses `1.3.3,` so I will deploy it right now using `1.3.6.crab1`

**Comment by ddaina** [comment]
I deployed crabserver in `test2` cluster using `1.3.6.crab1`. I have updated `crab-preprod-tw02` configuration to point to `test2` cluser instead of `testbed` and would suggest to keep it like this for a few days so that all submitted tasks would go to `test2`. If agreed, I would update `crab-preprod-tw02` puppet profile so that it would not overwrite my changes to config file.

Regarding crabcache - how I am supposed to deploy and test it?

**Comment by belforte** [comment]
I agree with this plan.
As to crabcache:
you can deploy it on test2 cluster the same way you did for crabserver, then it is a matter of
crabserver (REST) configuration which crabcache service it points to, what is the "mode" used by crabserver on test2 atm ?
If it is e.g. `cmsweb-test` it aready points to crabcache running on test2"
https://gitlab.cern.ch/crab3/CRAB3ServerConfig/blob/master/cmsweb-rest-config.json#L33-36

so it will be tested whenever crab task are submitted to test2

**Comment by ddaina** [comment]
great, thanks!

Currently mode points to `cmsweb-preprod`, meaning `https://cmsweb-testbed.cern.ch/crabcache`.  Should we switch it to `cmsweb-test` for good?

**Comment by belforte** [comment]
yes, I think that's what we meant `cmsweb-test` to be used for. At some point we needed to test `cmsweb-preprod` to validate it for using in testbed and k8s-testbed clusters, as you may remember. We just forgot to reset cmsweb-test2 to its purpose: test clusters for developers.

**Comment by ddaina** [comment]
I deployed crabcache, so now all submitted tasks to `preprod` will be pointed to crabserver and crabcache using `1.3.6.crab1` on `test2` cluster.

**Comment by belforte** [comment]
careful, `preprod` does not necessarely mean 'cmsweb-test2.cern.ch`
 https://github.com/dmwm/CRABServer/blob/67f8ba0a27dcfbd072ec8ec31a613ef7137061b3/src/python/ServerUtilities.py#L33

You may rather want to submit to `test2`

**Comment by ddaina** [comment]
sorry, my bad - wrong wording. I meant that both on client and TW side`config.General.instance` should be set to `other` and `config.General.restHost` with `config.General.dbInstance` should accordingly point to `cmsweb-test2.cern.ch` and `preprod`. I did that to TW on `preprod-tw02` and for my submissions on client side.

We could set `config.General.instance` to `test2` but currently `test2` points to `preprod` and `prod` DB, while `test2` uses `dev`. :-( need to re-deploy secrets and point it back to `dev` instead of `prod`

**Comment by belforte** [comment]
hmm
> We could set config.General.instance to test2 but currently test2 points to preprod and prod DB, while test2 uses dev. :-( need to re-deploy secrets and point it back to dev instead of prod
maybe current  CRABClient does not have up to date ServerUtilities.py ?
Or am I missing something ?
I need to go somewhere now, when I can I'll check what happens by selecting `instance=test2` in submission configuration file.

**Comment by belforte** [comment]
ah.. you are right. cmsweb-test2 + preprod DB instance is not a predefined configuration.

**Comment by ddaina** [comment]
I will try to re-deploy secrets. What if instead changing access from `prod` to `dev` we simple add new section to current secret and make it possible to access all 3 databases depending on the need?

whatever is the decision tho, high chances that I will mess up things in `test2` and it will be down for a while...(:

**Comment by belforte** [comment]
surely we do not want to do that now for testing WMCore.
Eventually I believe that test2 cluster should not have access to PROD database. Simply to fell more free to hack and mess around.
But don't touch it now.

**Comment by belforte** [comment]
I submitted a test task to `test2` as well, and it worked OK. sandbox was written to crabcache and later retrieved by schedd.

**Comment by ddaina** [comment]
same for me, all worked fine. 

I would say that we can update spec files in cmsdist, ask Imran to include it into next deployment and close this ticket since crabserver, crabcache and crabtaskworker with the new tag works fine.

**Comment by ddaina** [comment]
I have updated cmsdit [repo](https://github.com/cms-sw/cmsdist/pull/6178) with new tag and will ask Imran to deploy it to prod. 

I will do a crab-preprod-tw02 clean up and point it back to use `preprod` instance instead of `test2` cluster:
https://github.com/dmwm/CRABServer/blob/67f8ba0a27dcfbd072ec8ec31a613ef7137061b3/src/python/ServerUtilities.py#L33

I am closing this issue.
