### ISSUE TITLE
make env/start/stop scripts more uniform for TW and Publisher

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6131]
- [x] start.sh   change the Publisher one to use same definitions of test/debug/private as TW, add same comments... etc. basically make last part the same and look into using a common script. Done in https://github.com/dmwm/CRABServer/pull/6132

- [ ] env.sh here the Publisher one is more advanced. Should get rid of MYTESTAREA in TW and replace with e.g. TASKWORKER_ROOT (which is already defined but not consistently used)

- [ ] add --config option to TW's SequentialWorker so can use same syntax to start it ad for MasterWorker (and as done already for Publisher)

- [x] stop.sh  for Publisher is already an open issue #6099

**Comment by belforte** [comment]
Maye in the end I should do like for TaskWorker:

- there is top directory /data/srv/TaskManager or /data/srv/Publisher pointed to by an env. cat. $PUBLISHER_HOME or $TASKWORKER_HOME
- the various scripts are placed there by the installation procedure
- below that there are directories for each version like now, with one linked to as $TASKWORKER_HOME/current
- define two env. variables to point to that current area: $PUBLISHER_CURRENTDIR and #TASKWORKER_CURRENTDIR, the latter will replace $MYTESTAREA . Thise defaults to $PUBLISHER_HOME/current and $TASKWORKER_HOME/current. This allows to run things from a different version w/o moving current symlink around.
- The above also requires to copy PublisherConfig.py from $PUBLISHER_HOME (where it is placed by installation) to $PUBLISHER_CURRENTDIR i.e. /data/srv/Publisher/current so that config. files stay with their corresponding version
- properly use $TASKWORKER_HOME, $TASKWORKER_CURRENTDIR and $TASKWORKER_ROOT in TaskWorker/start.sh

**Comment by ddaina** [comment]
Maybe I am missing something, but do we need to worry about these two points:

> 
> - below that there are directories for each version like now, with one linked to as $TASKWORKER_HOME/current
> - define two env. variables to point to that current area: $PUBLISHER_CURRENTDIR and #TASKWORKER_CURRENTDIR, the latter will replace $MYTESTAREA . Thise defaults to $PUBLISHER_HOME/current and $TASKWORKER_HOME/current. This allows to run things from a different version w/o moving current symlink around.
> 
> 

in the container we can have only one release, so such thing as running different version from the same container would not happen. And in this case I would question  at all  if we need symlink from `$RELEASE` to `current` since that one and only `$RELEASE` in the container is what we are running. 

I understand that in some cases we might want to run TW or Publisher not in the container what basically means that we have more than one release in the machine. In this case I agree with the sequence that you defined. 

Then,

> The above also requires to copy PublisherConfig.py from $PUBLISHER_HOME (where it is placed by installation) to $PUBLISHER_CURRENTDIR i.e. /data/srv/Publisher/current so that config. files stay with their corresponding version

In the current TW setup we have this mount point  `/data/container/cfg/ : /data/srv/TaskManager/cfg/ ` and then this symlink defined in the `install.sh` script: 

https://github.com/ddaina/CMSKubernetes/blob/crabtaskworker/docker/crabtaskworker/install.sh#L36-L38

I see that [install.sh](https://github.com/dmwm/CRABServer/blob/master/src/script/Deployment/TaskWorker/install.sh) script which is used to install TW in private VM and [install.sh](https://github.com/ddaina/CMSKubernetes/blob/crabtaskworker/docker/crabtaskworker/install.sh) script which is used to install in container differes from each other as they are starting to server different needs. It is yet not in GH, but yesterday I made even more changes to the install.sh scrip to make it possible deploy TW and Publisher with one Dockerfile.

**Comment by ddaina** [comment]
Or in other words, do we want to support both installation ways?

**Comment by belforte** [comment]
looks like you nailed it
> Or in other words, do we want to support both installation ways?

**Comment by belforte** [comment]
Thanks @ddaina for having listed the relevant differences when running in a container. That helps as I was not fully aware.

Even if it means a bit more work for me, maybe we should  aim to have in the repository what's needed/useful for running as container. Then if I need some additional/different utility script to speed up testing in my VM should have something different.

All in all, if we have one container where things can be redirected to run from /data/user (i.e. `sh start.sh private` and `sh start.sh debug` work well) it would be enough. We always had this "developer container" in the todo list, all in all. Maybe there is nothing to do but add a mount point at start time ?

The only thinkg which puzzles me is how to deal with possible backward incompatible changes in the configuration file. There's a tension between "config outside the container to make it easy to tune production settings" and "configuration inside a specific version so it makes easy to roll back etc.".

**Comment by belforte** [comment]
this is now part of #6417. Close
