### ISSUE TITLE
Validate change for RUCIO in #6140 

### ISSUE THREAD

**Issue by dciangot** [dmwm/CRABServer#6154]
As already mentioned in the PR (https://github.com/dmwm/CRABServer/pull/6140) the changes to be tested are the following:

- [x] disable direct stageout when using rucio (instructions for using rucio in dev crab instance are here https://twiki.cern.ch/twiki/bin/view/CMSPublic/RucioUserDocsData

- [x] manage Rucio failures --> propagating failure to transferdb. To test this we might need a lot of statistics

- [x] use the definitive rucio user namespace: /store/user/rucio/ --> REST has to allow this. To do that serverutilities has been changed and we might need to see if any of the changes are destructive in unexpected way

@belforte who is going to be able to test this? I did already, but I can be a lot biased. How do you suggest to proceed?

**Comment by belforte** [comment]
OK. The critical part is the REST since there we need to go by CMSWEB monthly cycle.
The previous two items are safe and only affect TW which we already agreed to deploy in production.
I do not see the need to do more testing for those. Is this OK Diego ?

There are useful changes for TW in this tag even if it can't be used for Rucio because of the REST issue so @ddaina please update production.

But the change for REST is in a piece of code used by all tasks, and even if by reading it looks fine, we need to be extra careful.

Action items
1. @ddaina  (or @sharmaprajesh ) deploys the new REST tag v3.200913 on K8s test2 cluster (so we do not bug Imran)
2. @belforte  will submit jobs with different LFN and verify the last part.
3. @dciangot  will also submit and verify that it is as he want.
4.  @ddaina makes a PR for Imran to put the new tag in the testbed so we are all set for October deployment

**Comment by dciangot** [comment]
ok for me

**Comment by belforte** [comment]
> ok for me
thanks Diego. So I marked the first two items in the list at the top as done.

**Comment by belforte** [comment]
@dciangot the new REST is now in preprod. Please test. https://hypernews.cern.ch/HyperNews/CMS/get/webInterfaces/1744/1.html

**Comment by belforte** [comment]
I tested with various LFN patterns and it is all good from my sides. @dciangot it will be good to know that this works for what Rucio needs as well so we can give Imran the OK for deploying in production.

**Comment by dciangot** [comment]
@belforte I confirm. All good with the RUCIO workflow.

**Comment by belforte** [comment]
thanks !

**Comment by belforte** [comment]
sent green light for release in next CMSWEB monthly update: https://gitlab.cern.ch/cms-http-group/doc/-/issues/234#note_3797090
