### ISSUE TITLE
support CMSSW in python3

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6204]
as CMSSW moves to Python3, we need to make sure that the Pset  parsing and tweaking in the job wrapper is done (and works) with the correct python.
May require replace current PSet manipulation with a new tool  which is part of CMSSW.

**Comment by belforte** [comment]
Same thing will be needed for CRAB Client, but since that runs inside CMSSW scram env, should sort of come for free as long as code is py3 compliant.

**Comment by klannon** [comment]
The strategy that we took for WMAgent was to *decouple* the CMSSW and WMCore python environments, so WMAgent runs in an independent version of Python (currently Py2 but eventually Py3) than CMSSW.  We are achieving that decoupling by outsourcing the manipulation of the PSet to a separate script that lives in and is maintained by CMSSW.  That script runs in the Python environment of whatever CMSSW release is being used.

A big challenge with the CMSSW python version--that motivated this approach--is that old releases will remain Py2, so anything that interacts with CMSSW PSets needs to commit to supporting both Py2 and Py3 effectively indefinitely.

One thing that I didn't appreciate is that the CRAB client runs inside CMSSW's python environment.  Does the client also import from WMCore?  I ask because our hope was that eventually, WMCore would be able to drop Py2 support, but if we do that, we won't be able to have CRAB clients running from old CMSSW releases which only support Py2.

Let me start by tagging @davidlange6 and @khurtado here since they've done most of the work on the CMSSW and WMAgent pieces respectively.

**Comment by belforte** [comment]
Thanks @klannon . You are completely correct. And that's indeed something that I have to sort out. I have started talking about it with Alan and here's a first step
https://github.com/dmwm/CRABClient/issues/4940
which I could not follow up on yet.
My hope is that a few critical classes in WMCore may stay py2 compatible forever. Ideally it is not much to ask...
But I think we can make things work nevertheless.

In the end what CRAB Client really need is a way to make authenticated http calls to CMSWEB. That comes currently form WMCore and is a heavy dependency. I do not know if CMSSW has an alternative to offer... at worse we can always fork a curl command, call rate is low and there's no performance penalty to worry about. If anything, I am more annoyed by the fact that Rucio client breaks CMSSW scram env. Let's not discuss Rucio here though.

**Comment by belforte** [comment]
this is now well covered by a few other more detailed issues. No need to have it around as a "cover".
