### ISSUE TITLE
stop using CMSRucio.py

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6225]
it appears a useless complex layer that we can do w/o
and rather call directly Rucio Client. 

Also investigate if possible to use WMCore API instead of directly calling Rucio Client.
Should hopefully allow cleaner code and put on WMCore side the task of
documenting details of how to use Rucio.

**Comment by dciangot** [comment]
So, at this stage I'm currently working on moving everything to RUCIO client python bindings.

Anyway taking the occasion of this re-write, I'd like to introduce a parent general Class for TaskProcess, in order to keep it clean and ready to be used with both FTS and Rucio backend.
I see something with 2 public methods:
- TaskProcess class:
  - init()
  - submit_transfer()
  - monitor_transfer()

To reduce the amount of changes, I'd start only to apply this to the Rucio case, and then, if we want to, expand this to FTS case in a different ticket.

@belforte what do you think?

**Comment by belforte** [comment]
Are you sure that it is worth  the effort ? You may easily end with two completely different implementations anyhow and no code sharing.  Maybe a single submit_transfer and monitor_transfer which does all that it can in common and then calls back-end specific functions ?

**Comment by belforte** [comment]
OTOH, commeting on initial issue, it is now clear that we do not want to add WMCore in the game here and rather code for the native Rucio python client.

**Comment by dciangot** [comment]
in #6872 this will be addressed adopting RUCIO CLI API directly on the transfer script

**Comment by belforte** [comment]
thanks Diego ! +1
For the record, let's summarize:
We came to the conclusion that WMCore Rucio class is not a generic wrapper, but something heavily customized for internal WMA/WMCore needs. And in agreement with WMCore developers have stopped using it everywhere. Rucio python client is clean and simple enough that using it directly makes code easier to read and to change.
