### ISSUE TITLE
[build] Drop `py2-mysqldb` from `crabserver.spec` "Requires" list

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#6228]
[crabserver.spec](https://github.com/cms-sw/cmsdist/blob/130fe6e899f1a2a625ff6b248e93cd2efaac2db5/crabserver.spec) lists [py2-mysqldb.spec](https://github.com/cms-sw/cmsdist/blob/comp_gcc630/py2-mysqldb.spec) as a dependency.

`py2-mysqldb` builds `v1.2.4b4` of [MySQLdb - github](https://github.com/farcepest/MySQLdb1/tree/0f8d86cc8729efee304b15ae8c022bbc05f844db), but `MySQLdb` does not support python3.

I had a quick look at CRABServer repository and I could not find any import of `MySQLdb`, in particular I could not find

```python
import MySQLdb
# or
import _mysql_exceptions.py
```

Thus, I would consider safe dropping the dependency from `py2-mysqldb` in `crabserver.spec`.

Do you agree? Did I miss something?

**Comment by amaltaro** [comment]
Thanks Dario!

**Comment by belforte** [comment]
Well.. yes and no. Let me explain.
CRAB picks DataBase via WMCore. So if we wanted to deploy CRABServer on MySQLdb we would
activate lines like 
` if request.db['type'].__name__ == 'MySQLdb':` 
in ./src/python/WMCore/REST/Server.py
I do not know how that eventually imports the actual MySQLdb interface library, since WMCore does not have that import either, most likely via sqlalchemy which I assume has a dependency from MySql in one way or another.
In other words, you can try, but I believe that simply dropping the dependency either gives an error from sqlalchemy at buld time, or only crashes painfully in case one asks the code to talk to MySQL (the latter is hard to try for sure, let's not do it!),

That said, developers have been very good originally to write code which supports both DB's, but in practice we have never ran CRAB on MySql, so if you tell me "only use Oracle from now one", I have no problem.

I hope I answered the question. Indeed I do not have clear cut wisdom here, but would say: let's do whatever you decide for WMA/DBS and will work for CRAB as well.

**Comment by belforte** [comment]
@mapellidario @amaltaro I am keeping this open. Take your time and let me know how it ends !

**Comment by amaltaro** [comment]
Okay. I still have to test how WMAgent deals with MySQL/MariaDB without that dependency. This is something I don't fully understand, but if WMAgent works without it, I see no reason why CRABServer wouldn't (even though it has never been enabled against MySQLDB backend over the last few years...).

**Comment by belforte** [comment]
I fully agree. Maybe we can even close this ?

**Comment by amaltaro** [comment]
I'd leave it opened until we really get rid of that dependency from our spec files.

**Comment by belforte** [comment]
py2-mysqldb was successfully remove from crab spec files.
https://github.com/cms-sw/cmsdist/commit/cf51d11ab1e7022af914b7656ff97c22021a5063#diff-06b03e7a1e5ff9a166627fc1b08dff0fe1c995ff38bb0f42e0c1c996022f463f
