### ISSUE TITLE
Submission failure when file from dataset has no parent

### ISSUE THREAD

**Issue by ckoraka** [dmwm/CRABServer#6438]
When trying to submit a task using a parent dataset in DBS as secondary input source ( using either useParent = True or by specifying the dataset via secondaryInputDataset in the CRAB configuration .py), if a file w/o parents exists in DBS, the crab server responds with the following error message :

Failure message from server:	The CRAB3 server backend refuses to submit jobs to the Grid scheduler
				because you specified useParents=True but some your files have noparents.
				Example: /store/mc/Run3Winter20DRMiniAOD/DYToLL_M-50_TuneCP5_14TeV-pythia8/MINIAODSIM/DRFlatPU30to80_110X_mcRun3_2021_realistic_v6-v2/240000/60E027C5-A094-1F49-9555-5DFD417ED1FF.root

Even after trying to skip the specific lumisections corresponding to the file causing the failure by using a lumimask, the task still fails submission.
@belforte

**Comment by belforte** [comment]
thanks @ckoraka can you also give the the name of the input dataset ?

Fore reference, more info is in 
https://hypernews.cern.ch/HyperNews/CMS/get/computing-tools/5618/1/1/1/1.html

**Comment by ckoraka** [comment]
@belforte Yes sure very sorry for omitting this! The input dataset is the following :
 
/DYToLL_M-50_TuneCP5_14TeV-pythia8/Run3Winter20DRMiniAOD-DRFlatPU30to80_110X_mcRun3_2021_realistic_v6-v2/MINIAODSIM    
 
and the corresponding parent dataset is this one : 
 
/DYToLL_M-50_TuneCP5_14TeV-pythia8/Run3Winter20DRMiniAOD-DRFlatPU30to80_110X_mcRun3_2021_realistic_v6-v2/GEN-SIM-RAW

**Comment by belforte** [comment]
time to work on this. moving to TOP

**Comment by belforte** [comment]
in the initial HN thread I incorrectly assumed that lumimask is applied first and therefore users could skip such bad files in that way. But in reality lumimask is only applied in the Splitter step.
The submission is instead stopped in the DBSDataDiscovery step by
https://github.com/dmwm/CRABServer/blob/92be0c88ac214f283ca6260562d7be3a7e2548be/src/python/TaskWorker/Actions/DataDiscovery.py#L55-L59

So I have following possibilities:
1. simply skip files with no parent, like done for invalid files in https://github.com/dmwm/CRABServer/blob/92be0c88ac214f283ca6260562d7be3a7e2548be/src/python/TaskWorker/Actions/DataDiscovery.py#L44-L48
2. find a way to make it possible for the user to decide if to skip those files or not (but adding a param to CRAB configuration is a lot of work)
3. leave as is and user will have to get those files marked as invalid in order to be able to skip them

The danger with 1. is that the warning message goes un-noticed and the user think of processing the full dataset even if this is not the case.
The problem with 2. (beside the work) is that like many other configuration parameters meant for exceptional use (allowUndistributedCmssw e.g.) it sticks in passed-around configuration files and users miss a piece of data w/o even a warning message.
While 3. is sort of "rock solid", but surely annoying in case skipping that bad file is not a problem.

@ckoraka based on your use case , what would you have liked to happen ?

**Comment by belforte** [comment]
above commit https://github.com/belforte/CRABServer/commit/3652ddd727d47490f39c934e33250df83bf53a6f implements 1. and it is now included in https://github.com/dmwm/CRABServer/pull/6684

**Comment by ckoraka** [comment]
@belforte thank you very much for following up on this issue! What I would have liked to happen is somehow simply skip the files with missing parent , so from the three solutions you propose I would would say [1] indeed best describes this, though I fully agree with your point [3], that files with no parent should not be valid the first place.

**Comment by belforte** [comment]
thanks @ckoraka . I got convinced that this is the best solution, in the end is the same output that one would get if those files were marked INVALID in DBS.
