### ISSUE TITLE
can't roll back rest deployment with Jenkins

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6511]
I used Jenkins to deploy crabserver v4.210406 on test2
It did not work as I liked (requires the rest config to point to S3 for crabcache even
if it may not be used) so I wanted to roll back to v4.210401
but when I try it exit immediately with failure w/o even trying to deploy
https://cmssdt.cern.ch/dmwm-jenkins/job/CRABServer_Deploy_Server/57/console

maybe a flaw in the logic of the check ?

**Comment by ddaina** [comment]
thanks @belforte 

it failed because before actual crabserver update in given cluster, jenkins checks which versions is currently running in cluster X (${currentVersion}, see code snippet below). Given that crabserver is not running in test2 cluster now, i.e. https://cmsweb-test2.cern.ch/crabserver/dev/info returns `Service unavailable`, so Jenkins failed immediately. 

After the crabserver image update, Jenkins again checks which crabserver version is running in X cluster (${newVersion}) and if that version matches versions which was supposed to be deployed (${RELEASE_TAG}). 

Code snippet that prepares email configuration and for that uses ${currentVersion}, ${newVersion}, ${RELEASE_TAG} values.

```
#4. Check if update succeed and prepare email configuration
if [ "${newVersion}" == "${RELEASE_TAG}" ]; then
	result="crabserver image in ${REST_Instance} cluster was SUCCESSFULLY updated from cmssw/crabserver:${currentVersion}  to  cmssw/crabserver:${RELEASE_TAG} image tag."
else
	result="crabserver image update in ${REST_Instance} cluster from cmssw/crabserver:${currentVersion}  to  cmssw/crabserver:${RELEASE_TAG} image tag FAILED. Please investigate manually."
    echo "deploymentFailed"
fi
```

**Comment by belforte** [comment]
shall we change so that it deploys requested image even if nothing is running now ? or running but failing, as is the case at this moment.

**Comment by ddaina** [comment]
> or running but failing, as is the case at this moment.

Ok, doing it.

**Comment by ddaina** [comment]
problem fixed - now if crabserver is failing in given cluster, Jenkins will anyway update it to new tag. please give it a try and let me know if anything else has to be done. 

Also, i set job to sent emails to cms-service-crab-operators@cern.ch, but maybe it will take some time for the e-group to sync data.

one last thing, IIUC imagebot is not running in `test1` cluster, we need to ask Valentin/Imran to deploy it there.

**Comment by belforte** [comment]
I see that test2 has been rolled back, is that test enough ?
I forgot to set one flag in new egroup, but since I changed ownership to Caio already.. we need to wait until I can change.
For image bot, let's ask Imran and see what he says.

**Comment by ddaina** [comment]
> I see that test2 has been rolled back, is that test enough ?

I guess so :) we can always improve down the road

> For image bot, let's ask Imran and see what he says.

done.

shall we close the ticket?
