### ISSUE TITLE
fix reporting from Publisher of tasks with >1K aquired files

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6860]
see: https://github.com/dmwm/CRABServer/issues/6849#issuecomment-965513384
we nee to either change parsing in logstash or change Publisher log to avoid the additional `(***)` which currently flags task with more than 1K acquired files to be published.

All in all I am for removing those stars since the Grafana plot would now clearly show such situation.
Since this is not critical, I will only change in python3 branch and will be in production when me move Publisher and TW to Py3.

@ddaina FYI (sine I pinged you on this in #6849)

**Comment by belforte** [comment]
Anyhow grepping for lines like
```
2021-11-12 12:39:01,505:DEBUG:master:        475 : 211108_160650:gjinjing_crab_2018DPStoPsi2SJ_newSIMformal_filter_tighter_round4
```
seems very fragile, there is no real "telling" pattern there.
@ddaina any better advice on how to print things ?

**Comment by ddaina** [comment]
I would suggest to have lines like this:
```
2021-11-12 12:39:01,505:DEBUG:master:acquired_files: acquiredOK    475: taaskname
2021-11-12 12:39:01,505:DEBUG:master:acquired_files: acquiredWARN  475: taaskname
```

i.e. have additional word `acquired_files` (any other word will work too). this word will be keyword and allow to identify this specific log line. then we will make `acquiredOK` and `acquiredWARN` values of the attribute that will hold info about OK or WARNING situations. 

let me know if i am not clear.

**Comment by belforte** [comment]
thanks Daina. Let's for a slightly more terse variant

```
2021-11-12 12:39:01,505:DEBUG:master:acquired_files:   OK  475: taskname
2021-11-12 12:39:01,505:DEBUG:master:acquired_files: WARN 1475: taskname
```

**Comment by belforte** [comment]
I am only doing this in new Python3 branch since it is not urgent.
When we will see that plot is empty, we weill remember to change the `grok` expression in filestash !

**Comment by belforte** [comment]
closed via https://github.com/dmwm/CRABServer/pull/6861

**Comment by belforte** [comment]
@mapellidario @novicecpp as you may have noticed the plot of acquired publications by task is now empty. I.e. we are in the condition mentioned in the above comment https://github.com/dmwm/CRABServer/issues/6860#issuecomment-968979876

@novicepp can you add this to your list of things and look into modifying appropriately the `grok` expression ? pointer to the logstash config is in this other old issue https://github.com/dmwm/CRABServer/issues/6849#issuecomment-965513384 but I do not know how we go from changing https://github.com/dmwm/CRABServer/blob/edb15ba1633b4650ad22dda390946b6ff92577ae/src/script/Monitor/logstash/crabtaskworker.conf to having the change take effect, maybe need to re-deploy out logstash private instance.
This is not urgent, I guess you can work on it once you are done with the crabserver memory usage issue and before you start the exercise to crea crab-dev-tw02.

let me know if you like more background information on this.

**Comment by mapellidario** [comment]
> but I do not know how we go from changing ... to having the change take effect, maybe need to re-deploy out logstash private instance.

All the documentation should be in https://twiki.cern.ch/twiki/bin/view/CMSPublic/CRABlogstash . If it is not, then we can have a look together and improve the docs.

In any case, after you merged #6861 , we deployed to logstash https://github.com/dmwm/CRABServer/pull/6906 to match your changes. It is in branch `master` (i know, bad choice maybe), but this is the configuration that we have at the moment. 
I dont remember checking with more than one number, just `89` acquired files, so it is definitely possible that the current grok configuration does not match when we have more than 1k files.

Maybe it's worth aligning the logstash config in between the branches python3 and master before changing anything.

**Comment by mapellidario** [comment]
Since we are here, it may be worth having a look at why `data.blocks` is correctly reported an `int` (and can be quickly visualized as an histogram in kibana)

![image](https://user-images.githubusercontent.com/16376695/154235625-a18d5610-87f0-455e-8fb6-3bc2bc9f1fd4.png)

while `data.acquiredFiles` (which is what we are failing to properly parse in this issue) is not

![image](https://user-images.githubusercontent.com/16376695/154235749-c72c54c9-6cb1-4b86-9705-9839fd655b26.png)

**Comment by belforte** [comment]
OK. There's clearly a few things here which I do not know/understand and some fact-finding is needed.

**Comment by belforte** [comment]
maybe worth to move to separate issue. Sorry for having thought that solution was simple.

**Comment by mapellidario** [comment]
I just checked the grok pattern that i think we should have in production at the moment and it properly parses lines like

```plaintext
2022-02-16 10:22:43,014:DEBUG:PublisherMaster,413:acquired_files: WARN  1455 : 220216_074813:hwen_crab_add3_DPSto6tr_SKIM
```

but i do not see the corresponding lines in kibana. I am missing something as well.

**Comment by mapellidario** [comment]
While I was having a chat with @novicecpp to explain him our log stack, we found a couple of problems and fixed this issue.

![immagine](https://user-images.githubusercontent.com/16376695/154478969-540a72c3-ecee-4661-b198-81f4da658e23.png)

We now have a plot that shows the sum of acquired files, aggregated over 30min, both in "CRAB Overview dashoard" and "Task Worker Internals" dashboard.

- the main problem was that we were grouping the data by tasks, which means one data series for every task. If the plot has too many series, it complains with "too many buckets" and the query fails, leaving the plot empty. This happens when we select a time period longer than ~2d (empirically, some quick tests with selecting time ranges). If we do not aggregate by task, and sum all the contributions instead, the query is successfull.
- in https://github.com/dmwm/CRABServer/pull/6906/files we added a new filter, that matches the logs coming from https://github.com/dmwm/CRABServer/pull/6861/files , which has been included only in python3. `data.log_type:acquired_files` selects only log lines from py2-Publisher, `data.log_type:acquired_files_status` selects log lines only from py3-Publisher. The solution is to use the follwing query in grafana `data.log_type:acquired_files OR data.log_type:acquired_files_status`, so that we have a single consistent line across publisher deployments.

Other answers to my previous questions:

- in kibana, `data.acquiredFiles` is likely not recognized as a field that can be visualized/queried because it is not present in every log line. It is present only in `acquired_files` / `acquired_files_status`, not in `successful_publication`. Wa sugested to refresh the index pattern for ` monit_prod_crab_logs_publisher* `, with no success (thanks for the suggestion Wa! i would have never found that menu!). 
- in kibana, i did not find the lines with `WARN` for bad luck. Selecting a different time range all seems good. This was a nice discovery, that confirmed that we inserted the proper data into ES, which helped us to pinpoint the problem in grafana panel configuration.

![immagine](https://user-images.githubusercontent.com/16376695/154481632-cf2d89ef-7779-4f29-a9f7-843af6352be0.png)

Thanks Wa for the help! It would have taken me much more time to find the problem!

@belforte please add any comment. If you like the proposed solution, i think we can close this issue. If we really want to group the plot by task, than keep this issue open and we do some more investigation.

**Comment by belforte** [comment]
I am quite confused.
1. yes, it was "known" that the plot by task only works for short time range. But the point is exactly that I want a plot by which I can tell if one task is stuck. The old plot was useful to me.
2. Why do you worry about consistency of py2 and py3 versions of Publisher ? We only use py3 now.
3. did you do something to this plot ? Or should I read it as real and hence a sudden very serious probelm ? 
![Screenshot from 2022-02-17 13-43-11](https://user-images.githubusercontent.com/1837785/154484289-d427b9b5-768b-4b79-80a0-c529eeef835e.png)
4. I can not really parse the text in next to last bullet above. Was the problem solved or not ? Anyhow I do not really understand the problem. Would need some explanation

**Comment by belforte** [comment]
there is a real problem, submissions are also failing. https://mattermost.web.cern.ch/cms-o-and-c/pl/9qggmbh717bspb16h8y31jswta

**Comment by mapellidario** [comment]
1. Oh, I see now. Then there are some choices to make. We can select 
  - the time range (easy to change): 1d, 3d, 7d, 
  - the aggregation time / time bin size (requires editing the panel config): 30m, 1h 
  - how many tasks to show (requires editing the panel config): show only the top N tasks based on some metric, 
  - which tasks to show (requires editing the panel config): the metric used to select the top tasks. Can be either "taskname" alphabetically, number of log lines or sum of acquiredFiles across all points (sort of integral of the plot). The only informative one is sum of acquiredFiles.

  i made some tests and the next table shows how many tasks we can have in our plots at max, when changing the time bin and time range

   | | 1d | 3d (default in CRAB Overview) | 7d | 14d | 30d |
   |-|-|-|-|-|-|  
   | 30m | no limit | 300 | 100 | 50 | 25 |
   | 1h    | no limit | no limit | 200 | 125 | 50 |

  I would select a 30m time bin (quicker to populate the plot) and the top 200 tasks, so that even if we go back a few days we have the plot. This is an opinion and I am open to suggestions.

2. I want to keep support for `data.log_type:acquired_files` in case we need to visualize data from before 2022-02-10. In a month from now we can happily remove that OR.
4. no, it's not a problem. Just an inconvenience, we just can not filter/select log lines in kibana based on `data.acquiredFiles`. If we don't care about this, then it is not a problem.

**Comment by belforte** [comment]
OK. Well.. indeed if one task were stuck with a handful of files to publish which do not get through, it would be impossible to see anyhow. So I'd say to go with top 100 tasks.
We'll need in time to thing of some way to detect possibly stuck publications, or wait for users to report them !

**Comment by mapellidario** [comment]
For what concerns "fix reporting of tasks with >1k acquired files" i think we can close this issue.

Then, it would interesting to devise a way to discover tasks that are stuck with only few files to publish. Should we create a new issue? should we incorporate this in the huge "revisit crab monitoring"?

**Comment by belforte** [comment]
yeah, the " discover tasks that are stuck with only few files to publish" is too much vague for anything but "we'll work on monitoring".
