### ISSUE TITLE
add type check of Oracle binds

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#6880]
see discussion in  https://github.com/dmwm/CRABServer/issues/6830#issuecomment-976735955 and below.
In our tables we have only these column types:
- VARCHAR
- CLOB
- NUMBER
- TIMESTAMP

TIMESTAMP columns are filled inside SQL calls using calls like the following, so do not concern us.
```
UPDATE tasks SET tm_last_publication = UTC_TIMESTAMP()
```

CLOB and VARCHAR must be of type `string` (ref. https://cx-oracle.readthedocs.io/en/latest/user_guide/lob_data.html and also from Kate) and NUMBER must be of type `int`  (from Kate).

So the idea is to modify
https://github.com/dmwm/WMCore/blob/4b6676a4350addd15b6e9abe48a4e41e5217d920/src/python/WMCore/REST/Server.py#L1666
of which CRAB is the only user and make sure that bind values passed to the `execute` and `executemany` methods in there are only of type `string` or `int`.

To be decided whether to log the problem or raise a fatal exception and make the http call fail (or crash the REST ? or .. ?)

Chances that we mix strings and ints at this point in CRAB life are basically zero so I would not bother to find out every time what the exact type should be, simply make sure that it is one of the allowed ones. But we should make sure that we do no mix strings and bytes !

We could make a new WMCore tag, or maybe clone this in CRABServer repository and use from there at least initially to speed up checking.

It would be wise to keep such test until we have fully migrated to python3 all TW and Publisher code.

@mapellidario this is just  an idea. Feel free to shoot it down.

**Comment by mapellidario** [comment]
Eventually we landed on this implementation: https://github.com/mapellidario/WMCore/commit/23fef9beb426c3600ca8fa9a7c3687db4cb0f193, which is included in my private fork of WMCore https://github.com/mapellidario/WMCore/commits/crabserver-restpy3-specfile. 
The latest tag at the moment pointing to this branch is https://github.com/mapellidario/WMCore/releases/tag/py3.211214patch1. If we encounter a variable that is not py3-`str` (unicode) or `int`, then we raise and exception and the rest server returns http error 500.

The `crabserver` running in preprod atm contains this check. So far this error have not been seen. 

We can check if this has been raised with

```
ssh vocms0750
grep -r "Unexpected variable type about to be inserted" /data/s3/logs/cmsweb-testbed/crab-logs/crabserver/2021/12/
```

**Comment by mapellidario** [comment]
Lately we have been extensively running the CRAB REST server with these changes in place.

No occurrence of any problem with the oracle binds have been found.

I took dmwm/WMCore/master, applied the commit https://github.com/mapellidario/WMCore/commit/23fef9beb426c3600ca8fa9a7c3687db4cb0f193 (mentioned above) on top of it and created several tags in my private mapellidario/WMCore repo, such as [mapellidario/WMCore/1.5.7.pre5](https://github.com/mapellidario/WMCore/releases/tag/1.5.7.pre5). Such tags have been used to create docker images.

We run such images in 
- preprod: from late 2021-12 to 2022-01-25 ~15:00 cern time, with several tags.
- prod: from 2022-01-25 ~50:00 cern time to 2022-01-26 at 12.13 cern time. with tag `py3.220120`, which used tags from mapellidario/WMCore

Since 2022-01-26 at 12.13 cern time, in prod we have been running `py3.220124`, which uses tags directly from dmwm/WMCore, without the check on oracle binds.

Closing with this comment
