### ISSUE TITLE
WMStep for FWLite jobs

### ISSUE THREAD

**Issue by ericvaandering** [dmwm/CRABServer#701]
At some point we need to support FWLite jobs in addition to cmsRun. CRAB2 does not really support this except through writing a custom script, which is too difficult, especially for the target FWLite user.

Not assigning a milestone to this.

**Comment by matz-e** [comment]
Just had a discussion with Marco about this after looking at some code.  It looks like writing a WMStep, Executor and Template would be fairly difficult to get right, and I'm not sure that the complexity would be worth the effort.  Unifying what we have for CMSSW and `scriptExe` currently (i.e. calling `cmsRun` manually) would greatly reduce the code complexity.

Looking @xshi's setup, we already pass through the proxy in the current code in git, and bits that are really missing for FWLite support would be removing the requirement of the job report file and passing the input files and mask in a sensible way (or just require file based splitting).  Then I would also think that the python libraries should be included in the sandbox.

**Comment by PerilousApricot** [comment]
Looking to other requests people had, the benefit of making a WMStep for FWLite processes is it adds the ability to trivially run multiple analysis steps in one job.

**Comment by matz-e** [comment]
To be fair, writing an executor does not seem to hard, I'm more confused by the complexity of `CMSSWStepHelper`.  What would the FWLite requirements be from your side?

I should also note that it looks to me like we're currently creating 3 release areas for one execution of the CMS run script, 2 of which seem to be created by WMStep…

**Comment by PerilousApricot** [comment]
Hi Matthias-

I think there's not a lot of requirements, per se. There's always just the general idea of wanting to make "easy things easy and hard things possible". FWLite (or even any arbitrary scripts) would be to have a contract between the grid side of "we give you arguments this way" and "you return an FJR-esque thing back to us". If that contract existed, it would be easier then for someone to do the next logical thing and provide "standard" boilerplate for analyses to use.

For instance, in PyFWLite, you do the following:

```
from DataFormats.FWLite import Events
files = ['file1.root', 'file2.root']
events = Events(files)
for event in events:
    # analysis stuff here
```

With a well-defined contract, Events and the C++ equivalent could be extended readily to accept an arbitrary input sequence instead of just a list of file names. A similar argument could be made on the backside for scripts to report back information about their outputs. A series of defined helper functions would go a long way to making it viable to have arbitrary executables be first class citizens.

```I should also note that it looks to me like we're currently creating 3 release areas for one execution of the CMS run script, 2 of which seem to be created by WMStep…```

The bonus of fixing existing code instead of starting from scratch is that you'd also benefit the other users of the existing code. There's been gigahours of WMStep running time at this point, a lot of the subtle kinks have been worked out over the course of however many years (4? 5?) the code's been in production. If there's 3 release areas for a single CMSSW job, then that would be a new wrinkle that could be fixed and benefit everyone in the process.

FWIW, ```cmsswStepHelper``` is just a series of helper functions around a ConfigurationSection object. The idiom with ConfigurationSections is that the actual configuration itself is bone-simple. You can't even set arbitrary objects as values in there, much less have each sub-bit of the configuration tree have custom methods. ```cmsswStepHelper``` is just a placeholder for how you would manipulate a ConfigurationSection object. Since FWLite scripts are a different ball of wax, you don't have to worry about reimplementing it.  For instance:

https://github.com/dmwm/WMCore/blob/b14ef269d6acddb15b75770b32e6ac1c47a4d379/src/python/WMCore/WMSpec/Steps/Templates/CMSSW.py#L111

Doesn't make any sense for FWLite.

**Comment by matz-e** [comment]
Hi Andrew,

Yes, a well-defined contract definitely seems to be missing here.  I'm not sure what can be done on the side of inputs, my intuition would be to provide some text/JSON files to exchange the information rather than shoving everything into the argument list.  As far as the FJR-ish output goes, I think that would be a lot shorter than what `cmsRun` is currently producing.  Maybe a skeleton would have to be provided by the step, with some bits to be filled in with user-supplied data.

As far as different `WMSteps` go, everytime I think about this issue, in terms of running distributed computing, it would be nice to even go back another step.  Rather than duplicating the CMSSW setup in the CMSSW step for FWLite/arbitrary executables, I think it would be good to have a common setup for CMSSW and then layer the bits for `cmsRun` and FWLite/arbitrary scripts on top of that.  And getting that right will take a while…

As far as the helper goes, I see how an FWLite-equivalent would be very lightweight.  But I also haven't fully grokked the call-structure around the helpers, either.  Reading your description, I would think that the configuration is equivalent to a C-struct, and the helper is the collection of manipulation functions for the struct (thinking pure C, that is).

**Comment by belforte** [comment]
IIUC that down the road you want to make it possible to run multiple steps in the same job, it may be better to keep the freedom to use different CMSSW versions in the different steps. All in all cmsrel is prettty quick when compared to "hours". Not clear that it will be ever needed, but cost is low.

**Comment by PerilousApricot** [comment]
@belforte - Since each CMSSW WMStep does a cmsrel seperately, you can already use different versions of CMSSW within the same job.

I agree that there should be some sorta JSON for the input, with the filename passed in via argument. But looking ahead to when people are actually using it, it'll probably save a lot of support email struggle to have a "blessed" interface between that file and the FWLite event loop, so people aren't rolling their own, failing, and then getting upset when their statistics are weird. The output stuff will probably end up being just the things that are needed from stageout and a couple bits for error code propagation.

**Comment by mmascher** [comment]
Adding label question and moving to October. That's because after talking with Dima/Stefano and others it was concluded that probably improving `scriptExe` and documenting how to use `scriptExe` for this use case is enough.

**Comment by belforte** [comment]
realistically: NO NEW FEATURES
