### ISSUE TITLE
add "timber" dashboard for CRABServer

### ISSUE THREAD

**Issue by novicecpp** [dmwm/CRABServer#7112]
We want "timber" like dashboard with datasource from crabserver itself, not apache logs.

More detail discuss here: https://its.cern.ch/jira/browse/CMSMONIT-458

**Comment by novicecpp** [comment]
Done

For moving all log to cmsweb-timber we track here: https://github.com/dmwm/CRABServer/issues/7206
And log format here: https://github.com/dmwm/CRABServer/issues/7181

**Comment by mapellidario** [comment]
I took the liberty of changing a couple of things:

- i changed the order of the panels, so that the top ones are now similar to "CRAB timber + pods", to make quick comparison between the two dashboards
- i changed the default time range for the same purpose
- i changed the list of available time bins for the same purpose
- i selected only the prod cluster by default, for the same purpose
- I added a variable called `crabserverpod` using all the terms from the `data.backend` column (using `data.agent_name` should have been the same, i still dont know why we have two columns that appear identical). I added a filter in all the panels on this variable

I hope you all like the changes, otherwise feel free to revert them!
