### ISSUE TITLE
Failed publication caused by temporary 403 error.

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#7289]
#### problem description

This morning around 10 we had a suspicious increase in requests that were denied with a 403, involving requests also from our own systems (TW and PUB) [1].

A user was affected and wrote a message to CMS talk [2]. I had a quick look with @novicecpp, we found that in his case PublisherMaster received a 403 when getting the filemetadata (at line [3]), `makeRequest` raised an exception because 403 is considered a terminal error and publisher master marked some those file publications as "failed".

#### temporary mitigation

We can write a script that marks the failed publications as "new", so that they can be picked up again by publisher at the next run.

#### long term mitigation

Maybe we can not consider the 403 as a terminal error when the "User-Agent" header contains publisher or taskworker.

#### references

[1] [grafana](https://monit-grafana.cern.ch/d/qUVV6S0Gk/crab-timber-pods?orgId=11&from=1654762534567&to=1654763896635&var-system=crabserver&var-method=All&var-api=All&var-code=403&var-metadataType=All&var-Filters=data.code%7C%3E%7C1&var-Filters=data.api%7C!%3D%7Cinfo&var-copy_of_system=All&var-cluster=cmsweb&var-env=k8s-prod&var-client=All&var-bin=10s&var-dnFilter=.*)

After filtering for HTTP code 403: 

![](https://mattermost.web.cern.ch/files/scdatyosmpncxp4m3yr6cps3sr/public?h=jslIUBSM-YrgJxUhmg8tdo7S5MQ1hhXqblBpY0SvxiI)

[2] https://cms-talk.web.cern.ch/t/crab-jobs-succeeded-but-publication-failed/11437

[3] https://github.com/dmwm/CRABServer/blob/8038dcf4a199832792eb8191d164e19c6fffd038/src/python/Publisher/PublisherMaster.py#L307

[4] https://github.com/dmwm/CRABServer/blob/8038dcf4a199832792eb8191d164e19c6fffd038/src/python/Publisher/PublisherMaster.py#L320

**Comment by belforte** [comment]
Can you remind me what 403 means and why we should handle it as success ?About the script for retrying.. user can do crab retry --publication. So I would not worry too much about thatsent from Stefano's mobile

**Comment by belforte** [comment]
also crab operators can issue crab resubmit --publication after a crab remakesent from Stefano's mobile

**Comment by mapellidario** [comment]
>  crab resubmit --publication

This is exactly what i was looking for! Thanks Stefano! As always, we have every tool already implemented :)

A 403 is "permission denied". I would not call it a "success", I am just suggesting that if the cmsweb FE says that our TW or Publisher certificated are not allowed to perform a request, we can assume that there is something wrong with the FE and try again the request. In any case, the effects have not been dramatic, so I would also live with the current situation

**Comment by mapellidario** [comment]
The `crab resubmit --publication` worked, so i closed this issue. Thanks Stefano!

**Comment by belforte** [comment]
It is a debatable point indeed. Usually permission denied is due to client missconfig. But in this case it would have made sense to retry. Pfff I am open to ideas,as long as they are simplesent from Stefano's mobileOn Jun 10, 2022 10:26 AM, Dario Mapelli ***@***.***> wrote:

crab resubmit --publication

This is exactly what i was looking for! Thanks Stefano! As always, we have every tool already implemented :)
A 403 is "permission denied". I would not call it a "success", I am just suggesting that if the cmsweb FE says that our TW or Publisher certificated are not allowed to perform a request, we can assume that there is something wrong with the FE and try again the request. In any case, the effects have not been dramatic, so I would also live with the current situation
