### ISSUE TITLE
Automatic splitting fails despite probes completed successfully 

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#7295]
### description

A user reported that the automatic splitting did not produce any job [1]. PreDag reports the output files of the 5 probes to be 0bytes, but the CMSSW logs say that the jobs wrote some events to the output files.

We need to investigate what is causing this problem.

[1] https://cms-talk.web.cern.ch/t/crab-splitting-failed-because-all-probe-jobs-failed/11627

**Comment by belforte** [comment]
thanks @mapellidario 
At first sight the probe job output is correct and the FJR has the output size info
https://cmsweb.cern.ch:8443/scheddmon/0196/llunerti/220613_151633:llunerti_crab_ParkingBPH1_Run2018A-UL2018_MiniAODv2-v1_v1/SPOOL_DIR/jobReport.json.0-1
but the PostJob writes 0 as size in https://cmsweb.cern.ch:8443/scheddmon/0196/llunerti/220613_151633:llunerti_crab_ParkingBPH1_Run2018A-UL2018_MiniAODv2-v1_v1/SPOOL_DIR/automatic_splitting/throughputs/0-1

relevant code is in 
https://github.com/dmwm/CRABServer/blob/8038dcf4a199832792eb8191d164e19c6fffd038/src/python/TaskWorker/Actions/PostJob.py#L1779-L1803

I do not see what may be wrong by looking, will need to run PostJob with debugger

**Comment by belforte** [comment]
it turns out to be the subtlest form of bug : situation not foreseen by original developer.

This task is extraordinary in the fact that probe job processes 8k events, yet produces a 3kbytes output. Original developer was expecting large numbers there so decided to round the `size/event` by using `//` which actually does a truncation so `3/8=0.375` is rounded to 0 in 
https://github.com/dmwm/CRABServer/blob/8038dcf4a199832792eb8191d164e19c6fffd038/src/python/TaskWorker/Actions/PostJob.py#L1801
I think that we simply need to keep 1 byte as lower value of size-per-event, so that the splitting algorithm will not have problems, or in other words replace the `//` operator with something which does `find the nearest integer larger to this float`. I do not know if python has a `round-up` function, but `int(size/event + 1.0)` may do

**Comment by belforte** [comment]
that's likely the same as `eventsize = (outsize // events) + 1`
