### ISSUE TITLE
enable IPV6 for S3 access

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#7299]
This is the natural follow up to #7268 

#### status

On hold, waiting for action by CERN IT [1]

#### description

When investigating #7268, we noticed that we do not have ipv6 access to s3.cern.ch from our pods, despite it being available (f.e. from lxplus). We should make sure that we can connect to s3.cern.ch with ipv6.

[1] https://cern.service-now.com/service-portal?id=ticket&table=incident&n=INC3147173

**Comment by belforte** [comment]
cmsweb-test* clusters in K8s now have been re-deployed by Imran and should have IPV6 properly disabled. @novicecpp kindly "volunteered" to verify and give green light to Imran for deployment in production so that we can close on this.
Link to Imran message: https://cms-talk.web.cern.ch/t/upgradation-of-cmsweb-test-clusters-07th-july-11-am/12503/3

**Comment by belforte** [comment]
some text is likely missing in previous (oldish) comments. The point is that in current cluster IPV6 appears present, but fails. In the new deployment we expect that host names resolution automatically offers only IPV4 addresses, w/o need to do it ourselves as per https://github.com/dmwm/CRABServer/blob/f4fb2efa4c75253f6e2c83cf24b34a5d503e5171/src/python/CRABInterface/RESTCache.py#L89-L91

**Comment by belforte** [comment]
resolved via https://github.com/dmwm/CRABServer/pull/7335
