### ISSUE TITLE
Validate Hadoop data available in condor raw source

### ISSUE THREAD

**Issue by dciangot** [dmwm/CRABServer#7312]
- [ ] sum of walltime per datatier
- [ ] avg cpu efficiency per read mode (onsite vs offsite)
- [ ] sum of walltime analysis vs production
- [ ] sum of walltime mc production vs analysis
- [ ] overall analysis success rate

**Comment by nutty7fold** [comment]
The full notebook and the plots can be acccessed at https://github.com/nutty7fold/cern-crab-data-analysis/tree/main/issue7312

**Comment by belforte** [comment]
nice work @nutty7fold ! Indeed you should stick with ExitCode. Alas it is not as a simple as to say "JobExitCode indicates error in the user application vs. Chirp_CRAB3_ExitCode indicates error due to the site", but hopefully we do not need to go into details of that. Simply there's an hierarchy of "which one carries the most complete and reliavle information" and hopefully most of the times all columns have same value.

**Comment by belforte** [comment]
We forgot to close, but this was completed successfully.
