### ISSUE TITLE
remove asourl and asodb column from DB

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7326]
- [x] remove them from DB Create.py script (no need to create them in new DB instances) #7328
- [x] physically remove them from DB schema :
   - [x] dev
   - [x] dev2
   - [x] preprod
   - [x] prod

**Comment by belforte** [comment]
Still need to cleanup the DB schemas

**Comment by aspiringmind-code** [comment]
Following SQL commands were persisted:
ALTER TABLE CMSWEB_ANALYSIS_DEV.TASKS DROP COLUMN TM_ASODB;
ALTER TABLE CMSWEB_ANALYSIS_DEV.TASKS DROP COLUMN TM_ASOURL;
ALTER TABLE CMSWEB_ANALYSIS_PREPROD.TASKS DROP COLUMN TM_ASOURL;
ALTER TABLE CMSWEB_ANALYSIS_PREPROD.TASKS DROP COLUMN TM_ASODB;
ALTER TABLE CMSWEB_CRAB_9R_DEV.TASKS DROP COLUMN TM_ASOURL;
ALTER TABLE CMSWEB_CRAB_9R_DEV.TASKS DROP COLUMN TM_ASODB;
ALTER TABLE CMSWEB_CRAB_9R_PREPROD.TASKS DROP COLUMN TM_ASODB;
ALTER TABLE CMSWEB_CRAB_9R_PREPROD.TASKS DROP COLUMN TM_ASOURL;

cmsweb_analysis_reqmgr instance didn't have these columns to begin with.
@belforte Please review.

**Comment by novicecpp** [comment]
> cmsweb_analysis_reqmgr instance didn't have these columns to begin with.

@aspiringmind-code you mean `cmsweb_analysis_reqmgr@int2r`, the one that you recreate the table yourself?
Or you mean production one `cmsweb_analysis_reqmgr@cmsr`?

And could you show us the crab task that run successfully after remove those column?

**Comment by aspiringmind-code** [comment]
@novicecpp I meant instance of the int2r database. I haven't touched the cmsr DB yet as it gives me the error that cmsr alias not found in tnsnames.ora. Also, the docs mentioned that directly accessing the production one is risky, so I thought I'd ask before making any changes there.

I'll need some help with testing.

**Comment by belforte** [comment]
What does it mean "commands were persisted" ?

**Comment by belforte** [comment]
Sounds like you know SQL better than me !  You can commit. And let's worry later about cmsr, e..g. when Dario is back and you sits next to each other

**Comment by aspiringmind-code** [comment]
Crab task working on the '/GenericTTbar/HC-CMSSW_9_2_6_91X_mcRun1_realistic_v2-v2/AODSIM' input dataset ran successfully after committing dropped columns in the intr database.

[vchakrav@lxplus997 myfirstcrabtask]$ crab status -d crab_20240705_121645
Rucio client intialized for account vchakrav
CRAB project directory:		/afs/cern.ch/user/v/vchakrav/crab/CMSSW_13_0_2/myfirstcrabtask/crab_20240705_121645
Task name:			240705_101649:vchakrav_crab_20240705_121645
Grid scheduler - Task Worker:	crab3@vocms059.cern.ch - crab-dev-tw05
Status on the CRAB server:	SUBMITTED
Task URL to use for HELP:	https://cmsweb-test11.cern.ch/crabserver/ui/task/240705_101649%3Avchakrav_crab_20240705_121645
Dashboard monitoring URL:	https://monit-grafana.cern.ch/d/cmsTMDetail/cms-task-monitoring-task-view?orgId=11&var-user=vchakrav&var-task=240705_101649%3Avchakrav_crab_20240705_121645&from=1720171009000&to=now
Warning:			The following sites from the user site whitelist are blacklisted by the CRAB server: ['T2_UK_SGrid_Bristol', 'T2_ES_IFCA', 'T2_DE_DESY', 'T2_US_MIT']. Since the CRAB server blacklist has precedence, these sites are not considered in the user whitelist.
Warning:			The following sites appear in both the user site blacklist and whitelist: ['T2_ES_IFCA']. Since the whitelist has precedence, these sites are not considered in the blacklist.
Status on the scheduler:	SUBMITTED

Jobs status:                    failed       		  0.1% (   1/1000)
				finished     		 98.9% ( 989/1000)
				running      		  0.1% (   1/1000)
				transferring 		  0.9% (   9/1000)

Publication status of 1 dataset(s):	new          		 98.9% ( 989/1000)
(from CRAB internal bookkeeping in transferdb)
					unsubmitted  		  1.1% (  11/1000)

Output dataset:			/GenericTTbar/vchakrav-autotest-1720174605-94ba0e06145abd65ccb1d21786dc7e1d/USER
Output dataset DAS URL:		https://cmsweb.cern.ch/das/request?input=%2FGenericTTbar%2Fvchakrav-autotest-1720174605-94ba0e06145abd65ccb1d21786dc7e1d%2FUSER&instance=prod%2Fphys03

Error Summary: (use crab status --verboseErrors for details about the errors)

   1 jobs failed in postprocessing step

Have a look at https://twiki.cern.ch/twiki/bin/viewauth/CMSPublic/JobExitCodes for a description of the exit codes.

Warning: the average jobs CPU efficiency is less than 50%, please consider to improve the jobs splitting (e.g. config.Data.splitting = 'Automatic') in a new task

Summary of run jobs:
 * Memory: 62MB min, 873MB max, 367MB ave
 * Runtime: 0:01:03 min, 1:00:17 max, 0:07:51 ave
 * CPU eff: 0% min, 27% max, 3% ave
 * Waste: 135:23:48 (51% of total)

Log file is /afs/cern.ch/user/v/vchakrav/crab/CMSSW_13_0_2/myfirstcrabtask/crab_20240705_121645/crab.log

**Comment by belforte** [comment]
Very well. Let's mark as done then !
