### ISSUE TITLE
Have a configuration option to make CRABServer logs (not)verbose

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7429]
from meeting minutes (Oct 4):

Can we disable trace logs (sql/data) produced by WMCore? Only optionally. In general we should have a verbose vs. non-verbose for the log, keep production logs terse and only enable verbose in test or when need to debug subtle problems in production sort of for a few days.

**Comment by novicecpp** [comment]
We can disable trace logs from WMCore by setting `dbconfig['<dbinstance>']['<request_type>']['trace']` to `False` in [CRABServerAuth.py#L15 ](https://gitlab.cern.ch/crab3/crab-secrets/-/blob/eedd40bff2f718a8cc859cbf955c94aba0e8b5c2/kubernetes/sample/CRABServerAuth.py#L15)

But, it will make server produce annoying traceback's logs because trace not found when crab log try to formatting trace.
https://github.com/dmwm/CRABServer/blob/6f133bf4e360e712ba1f7e5f962fd29c0cfcc50e/src/python/CRABInterface/RESTBaseAPI.py#L181-L187

```
Traceback (most recent call last):
  File "/data/repos/CRABServer/src/python/CRABInterface/RESTBaseAPI.py", line 183, in filter
    record.trace_id = cherrypy.request.db['handle']['trace'].replace('RESTSQL:','')
AttributeError: 'bool' object has no attribute 'replace'
[25/Oct/2022:17:02:49] crabserver-69b464fd97-n8vtr 188.185.126.221:52958 "GET /crabserver/devthree/workflowdb?limit=2&workername=crab-dev-tw03&getstatus=HOLDING HTTP/1.1" 200 OK [data: 2258 in 16 out 8207 us ] [auth: ok "/DC=ch/DC=cern/OU=computers/CN=tw/crab-dev-tw03.cern.ch" "" ] [ref: "https://cmsweb-test12.cern.ch" "CRABTaskWorker/development" ]
```

**Comment by mapellidario** [comment]
You can change that code with something that does not require an exception, something like

https://github.com/dmwm/CRABServer/blob/6f133bf4e360e712ba1f7e5f962fd29c0cfcc50e/src/python/CRABInterface/RESTBaseAPI.py#L86-L87

for example

```python
trace = cherrypy.request.db['handle']['trace']
record.trace_id = trace.replace('RESTSQL:','') if trace else ""
```

In general, I would use exception only when we really need to catch an external problem, not when we need to check if a variable is defined. I would not abuse [EAFP](https://docs.python.org/3/glossary.html#term-eafp) too much

**Comment by belforte** [comment]
@novicecpp since this is assigned to you, shall we remove the "available" label ?

**Comment by novicecpp** [comment]
Done.

**Comment by belforte** [comment]
we can keep living with things as they are. CRAB Server is very stable now.
