### ISSUE TITLE
Start using DBSError codes in CRAB

### ISSUE THREAD

**Issue by mapellidario** [dmwm/CRABServer#7469]
This issue is very similar in spirit to https://github.com/dmwm/WMCore/issues/11365, but applied to CRAB.

Basically, we can start using the values at https://github.com/dmwm/dbs2go/blob/master/dbs/errors.go#L38 to have more insight of what happened on the DBS side in case of problems.

**Comment by vkuznet** [comment]
FYI: all new DBS error codes (128 and above) are already deployed to cmsweb and cmsweb-prod.

**Comment by vkuznet** [comment]
And, WMCore changes to use new DBS error codes are here: https://github.com/dmwm/WMCore/pull/11375

**Comment by belforte** [comment]
thanks Valentin !
We have started using these in CRAB Publisher hopefully this is in line with new way now: https://github.com/dmwm/CRABServer/blob/a43a10d461cee1bd58ee36ebadb43b5a7909c5df/src/python/Publisher/TaskPublish.py#L218-L268
We will have to make sure that there is no place where we rely in parsing exception messages, but IIRC, outside Publisher we talk to DBS via the WMCore DBSReader class, will that be changed to return DBSError ?

**Comment by belforte** [comment]
Thanks @vkuznet !!! We'll do

**Comment by belforte** [comment]
Time to do this !
We had an error in Publisher today [1] because our code does not properly handle this
```
  File "/data/srv/TaskManager/v3.240111-ac252900ca96a6784d9e561ca231c954/slc7_amd64_gcc630/cms/py3-dbs3-client/4.0.12/lib/python3.8/site-packages/dbs/apis/dbsClient.py", line 522, in __parseForException
    raise HTTPError(http_error.url, data['exception'], data['message'], http_error.header, http_error.body, serverCode(data))
RestClient.ErrorHandling.RestClientExceptions.HTTPError: HTTP Error 400: DBSError Code:125 Description:DBS Migration error Function:dbs.migrate.SubmitMigration Message:Migration request /Zto2Nu-2Jets_PTNuNu-40to100_1J_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer22EEMiniAODv4-130X_mcRun3_2022_realistic_postEE_v6-v1/MINIAODSIM#1d24b8c6-ef15-4ffc-8de6-ba80cb3a0d6e, id=0 Error: migration request /Zto2Nu-2Jets_PTNuNu-40to100_1J_TuneCP5_13p6TeV_amcatnloFXFX-pythia8/Run3Summer22EEMiniAODv4-130X_mcRun3_2022_realistic_postEE_v6-v1/MINIAODSIM#1d24b8c6-ef15-4ffc-8de6-ba80cb3a0d6e is already exist in DB with id=4392537
```

Note: DBSError Code 125 in there. Current Publisher code stops at HTTP 400 and marks all files as publication failed.
Unfortunately DBSError Code 125 is a generic `Migration Error` and we will need to parse the Description for the telling "already Iexist with id=...." so that we can switch to checking on that migration id instead. In the particular case of [1] I am not sure that current code will recover since that migration was "Failed"  and current code does not retry Failed publication assuming that they deserve manual investigation first.

Handling of failed migration aside, we really need proper reporting

corollary: that exception was only the json summary of TaskPublish.py, not in the log. Exceptions which lead to failure should be printed in the log !

[1] ] https://cms-talk.web.cern.ch/t/unpublished-crab-dataset/34859/10

**Comment by vkuznet** [comment]
Stefano, all DBS error codes are defined here: https://github.com/dmwm/dbs2go/blob/master/dbs/errors.go Said that, we may add additional codes for specific use cases but sometimes it may be very tedious process since it requires to parse corresponding ORACLE error. In particular, this error comes from this function https://github.com/dmwm/dbs2go/blob/master/dbs/migrate.go#L581 which return generic error and it is captured over here https://github.com/dmwm/dbs2go/blob/master/dbs/migrate.go#L674 and DBS error is created and returned  in  here https://github.com/dmwm/dbs2go/blob/master/dbs/migrate.go#L679. Therefore, if you need a new error you may request it in dbs2go issue and we may adjust the later line to return new kind of error, like MigrationRequestAlreadyExist (with newly assigned new error code). All of that can be easily done by @todor-ivanov if you'll request it based on information I provided here.

**Comment by belforte** [comment]
Thanks @vkuznet . I thought about asking for an ah hoc error code, but in this case we also need the ID of the already existing migration, i.e. there may be no alternative to parsing the full error text. Hopefully it will not change.

**Comment by belforte** [comment]
For DBS migrations we are already doing "the best we can". Other API's never failed so far other then "server down" which we simply retry. So this is not that urgent. Domote priority.

**Comment by belforte** [comment]
we are doing our best already. And have correct reporting of all problems. We will go back to this when we have an error where DBSError code helps. Wrapping all DBS client calls in something which prints it is an overkill.
