### ISSUE TITLE
fill properly tm_dbs_blockname and tm_block_complete in RUCIO_Transfers

### ISSUE THREAD

**Issue by belforte** [dmwm/CRABServer#7524]
now that updateRucioInfo API is available in REST
https://github.com/dmwm/CRABServer/blob/2cbd932bd64724dcbcca915f21665af1d9b5a08f/src/python/CRABInterface/RESTFileTransfers.py#L185-L198

usage example in https://github.com/belforte/utils/blob/master/notebooks/TestTransfersdb.ipynb

And from https://github.com/dmwm/CRABServer/wiki/ASO-via-Rucio the plan is:

* 1 rule per container
* 1 dataset each 100 file or when lumi limit is exceeded
* when a dataset is completed at least one of the files in it must be flagged via setting `block_complete` to `YES`

**Comment by belforte** [comment]
Findings from looking at code in https://github.com/dmwm/CRABServer/blob/master/scripts/task_process/RUCIO_Transfers.py 
* currently the file limit per dataset is not implemented 
* not clear if all files go in same dataset or if in some conditions a new one would be opened
* as long as there's one dataset there is also one rule, this must be kept moving role creation to when container is created
* why do we have `lfn2pfn` mapping code here instead of using Rucio's `lfns2pfns` ?
* global structures are not documented, must do this and find the correct way to fill dataset/DBS_block name in `filetransfersdb` table when inserting new files there.
* `task_process/transfers.txt` is opened and read 4 times
* logs are known to be too much verbose
* need a writeup of the procedure to test/debug RUCIO_transfers interactively on scheduler

**Comment by belforte** [comment]
bugs found
- [ ] https://github.com/dmwm/CRABServer/blob/2cbd932bd64724dcbcca915f21665af1d9b5a08f/scripts/task_process/RUCIO_Transfers.py#L237 the initial `/` is there already in `publishname` also `g.logs_dataset` is defined already
- [ ]

**Comment by belforte** [comment]
steps to implement the needed functionality
- [ ] register_replicas should not return list of names, but rather add success/fail info and dataset name into each replica dictionary so that information can be used when updating oracle.
- [ ] update_db should be changed to take alist of replica dictionaries as input ? Or maybe the needed info can be added to filedoc_for_db ? The the new updateRucioInfo api may even be not needed ?
- [ ] should not mark files as "done" (i.e. update lastline) unless info in CRAB DB was updated, and therefore be prepared for finding already processed files (which may be the case already)

**Comment by belforte** [comment]
my scratchbook:
lists from register_replicas are lists of LFN's or of oracle-ids ?

**Comment by belforte** [comment]
after discussion with @dciangot , some code reformatting is needed to implement internal bookkeeping as now sketched in the [wiki](https://github.com/dmwm/CRABServer/wiki/ASO-via-Rucio)

that overrides all above concepts/questions

**Comment by belforte** [comment]
work in progress on this is in https://github.com/belforte/CRABServer/tree/fill-block-info-from-RT-fix-7524

**Comment by belforte** [comment]
here's a contribution from Wa: https://github.com/belforte/CRABServer/compare/fill-block-info-from-RT-fix-7524...novicecpp:CRABServer:rucio_transfer_fill_info_to_db_for_publisher_upstream_belforte

**Comment by novicecpp** [comment]
Items need to discuss:

- [ ] How do we notify postjob that transfer is complete?
  - also, which condition?
- [ ] We do not handle the case where files in temp is gone. Both before and after transfer complete.
- [ ] We add new files as bulk (current default is 20) but current code will fail the whole bulk if fail. Should we fix it?
- [ ] What about direct stageout?
  - should we disable it for rucio transfers? or still enable it but add code to RUCIO_Transfers.py to add files to container later?
- [ ] Condition to stop execute RUCIO_Transfers.py?
  - From TODO: if replicas take > 12h to transfer, what shall we do?
- [ ] bookkeeping for monitoring replicas?
  - I am not sure because currently 1) we fetch all replicas status the whole container from container's rule ID. 2) we update all replicas to rest. 
    Then which level we want to optimize ? only part on update filetransfers table? or fetch and only complete block (need to add rule to each dataset to archieve this)?
- [ ] What about retry jobs (I remember we discussed sometimes ago, but I did not understand what is the solution).
- [ ] Why we need str.rjust(8, '0') at adler32 checksum?
- [ ] TODO: Broken site config in rucio (not 100% sure)
  - `T2_DE_DESY` Rucio expect `<prefix>/store/temp` but `lfn2pfns` return `<prefix>/temp` (at least it is valid path).
  - `T2_UK_SGrid_Bristol` no protocol available for `T2_UK_SGrid_Bristol_Temp` when get PFN from solving `T2_UK_SGrid_Bristol`.
- [ ] TODO: Test with production tasks
  - shadowing transfer
    - Need to disable fts_transfer files deletion.
  - grep random tasks from production and run ourselves in preprod?
    - less effort compare to shadowing transfer, submit user job in preprod can be automated.
- [ ] TODO: LOGS transfers (need to be done).
- [ ] TODO: 1 container for multiple tasks.
- [ ] TODO: Long way to go for better unittest/integration test.
  - It is spaghetti code.
  - Only simple testcase.
  - No integration code at all (It is done by hand for now).

**Comment by novicecpp** [comment]
Next to do list for RUCIO_Transfers.py
- [ ] update files in SPOOL_DIR to notify postjob that transfer is complete.
- [ ] add code to handle files that not-OK after threshold time has passed.
- [ ] check what happen to the `RUCIO_Transfers.py` script when files checksum is incorrect.
- [ ] Fix `add_replicas` to try again instead of fail them (It should not failed on this step).
- [ ] bookkeeping locks monitoring.
- [ ] Fix rucio config broken on site `T2_DE_DESY` and `T2_UK_SGrid_Bristol`.
- [ ] add comment in code that we will not do log transfer for rucio (until it requires by user).
- [ ] 1 container for multiple tasks.

**Comment by belforte** [comment]
I can not find the place in above lists, but IIRC the action on me was to explains how and when RUCIO_Transfers.py stops running. This is controlled in these lines:
https://github.com/dmwm/CRABServer/blob/18af83f510e5ff8579ad30a5073cc97af9c060a9/scripts/task_process/task_proc_wrapper.sh#L36-L51
combined with the `while True` look at the bottom of the script.

**Comment by belforte** [comment]
One more thing:
 * when user issues `crab resubmit` the DAG is restarted and a new `task_process_wrapper.sh` is started (as a condor job in local universe, `jobuniverse==12`) and again executes until the DAG completes (or it crashes).

**Comment by novicecpp** [comment]
Thanks Stefano. I will write this somewhere in our docs.

One question: how do you want to proceed on my stale PR [#7587](https://github.com/dmwm/CRABServer/pull/7587) ?
Do you want to review it by yourself or review it together in zoom chat (one Actions class at a time, total 3 Actions classes)?

I prefer to have someone crosscheck my code before merging it (It will merge to feature branch `rucio_transfers` in `dmwm/CRABServer` repo, but in the end, it will get merged to master). Then, I can close this issue and move on to https://github.com/dmwm/CRABServer/issues/7632 .

**Comment by novicecpp** [comment]
This issue is solved via this [commit](https://github.com/dmwm/CRABServer/commit/1a6dd1fd4117fc738aef612d83e50d98d2d83bf1#diff-cff0a0719b4ec8b470d2a039241db3675479d70b42212c530efd5d0cc62aab0b) (just work, another patch is incoming).
 Tracking other Rucio ASO issues in [#7632](https://github.com/dmwm/CRABServer/issues/7632) and closing this one.
