### ISSUE TITLE
Include SendVenvFolder test in Client Configuration Validation of gitlab pipeline

### ISSUE THREAD

**Issue by aspiringmind-code** [dmwm/CRABServer#8779]
Currently, Jenkins runs the SendVenvFolder test in CCV but Gitlab pipeline has it commented out as it throws an error of not finding venv folder. 
See [here](https://github.com/dmwm/CRABServer/blob/master/test/makeTests.py#L272C1-L284C72) 
Investigate and add this test as part of the pipeline.

**Comment by belforte** [comment]
and this test works when executed via Jenkins. DId you try to simply uncomment it ?

**Comment by aspiringmind-code** [comment]
@belforte  Yes, in the PR I have uncommented, that's why this issue is created as it is being left out of the Cv CCV PR.

**Comment by belforte** [comment]
I am really curious what happens differently in the pipeline which makes it fail. Feel free to point me at logs.

**Comment by belforte** [comment]
so the problem is that CRABClient is not setup with that script which I quoted, but by a new one
https://github.com/dmwm/CRABServer/blob/master/cicd/gitlab/setupCRABClient.sh
which is not simply "the old one copied to the new directory" as I thought. But at least lacks the lines which create the `venv` directory.

So fix is easy. But we need to check if there are other differences.

**Comment by aspiringmind-code** [comment]
Thanks Stefano for the quick diagnosis! Fixed in the [PR](https://github.com/dmwm/CRABServer/pull/8696) Closing this issue.
